export default {
  extends: ['stylelint-config-standard-scss'],
  overrides: [
    {
      files: ['**/*.{css,scss}'],
      ignoreFiles: ['website/out/**', 'lib/dist/**'],
      rules: {
        'alpha-value-notation': null,
        'at-rule-empty-line-before': null,
        'color-function-alias-notation': null,
        'color-function-notation': null,
        'color-hex-length': null,
        'comment-empty-line-before': null,
        'custom-property-empty-line-before': null,
        'custom-property-pattern': null,
        'custom/valid-theme-token': true,
        'declaration-block-no-duplicate-properties': null,
        'declaration-block-no-redundant-longhand-properties': null,
        'declaration-empty-line-before': null,
        'length-zero-no-unit': null,
        'no-descending-specificity': null,
        'no-invalid-position-declaration': null,
        'number-max-precision': null,
        'property-no-deprecated': null,
        'property-no-vendor-prefix': null,
        'rule-empty-line-before': null,
        'scss/at-mixin-pattern': null,
        'scss/at-rule-no-unknown': null,
        'selector-class-pattern': null,
        'selector-not-notation': null,
        'selector-pseudo-class-no-unknown': null,
        'selector-type-no-unknown': null,
        'value-keyword-case': null,
      },
    },
  ],
  plugins: ['./scripts/stylelint-valid-theme-tokens.js'],
}
