export const arrows = [
  'angle-left-b',
  'angle-right-b',
  'angle-up',
  'angle-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'left-arrow-to-left',
  'arrow-to-right',
  'top-arrow-to-top',
  'arrow-to-bottom',
] as const

export const actions = [
  'asterisk',
  'info-circle',
  'chart-line',
  'plus',
  'chart-line',
  'archive-alt',
  'arrows-merge-v', // (not unicons, personal mashup)
  'arrows-shrink-v',
  'apps',
  'user-check',
  'user-plus',
  'user-times',
  'check',
  'times',
  'trash',
  'download',
  'upload',
  'drag_and_drop',
  'copy',
  'pen',
  'left-arrow-from-left',
  'arrow-from-right',
  'resize-handle', // (not unicons)
  'arrow-resize-diagonal',
  'external-link-alt',
  'heart-solid',
  'heart',
  'heart_outline',
  'filters',
  'show',
  'hide',
  'link',
  'log_out',
  'menu',
  'more_android',
  'more',
  'move',
  'notification',
  'sign-out-alt',
  'bars',
  'ellipsis-v',
  'ellipsis-h',
  'move-arrow', // (not unicons)
  'bell',
  'print',
  'promote',
  'reset',
  'save',
  'search',
  'setting',
  'share-alt',
  'share',
] as const

export const miscellaneous = [
  'music',
  'sparkles',
  'rocket',
  'file-alt',
  'user-square',
  'book-reader',
  'file-question-alt',
  'sad-solid',
  'smile-beam-solid',
  'sad',
  'smile-beam',
  'sign-right',
  'exclamation-triangle',
  'exclamation-circle',
  'exclamation-octagon',
  'chart-pie',
  'paperclip',
  'chart-bar',
  'fire',
  'user-check',
  'apps',
  'trophy',
  'bookmark-solid',
  'bookmark',
  'bookmark_outline',
  'clock',
  'comment',
  'comment_outline',
  'contract',
  'write',
  'date',
  'department',
  'earth',
  'education_level',
  'email',
  'email_outline',
  'equal',
  'remove',
  'folder',
  'female',
  'male',
  'home',
  'information',
  'information_outline',
  'kanban',
  'language',
  'suitcase',
  'line_chart',
  'location',
  'lock',
  'lock_rounded',
  'flag_pointed',
  'mention',
  'user-circle',
  'user',
  'user_outline',
  'offer_status',
  'office',
  'origine',
  'phone',
  'phone_outline',
  'pin',
  'podcast',
  'search_people',
  'remote',
  'review',
  'review_outline',
  'salary',
  'euro_currency',
  'source',
  'question',
  'anniversary',
  'birthday',
  'celebrate',
  'star',
  'star_outline',
  'tag',
  'comment-alt-lines',
  'file-edit-alt',
  'illustration',
  'calendar',
  'users-alt',
  'globe',
  'graduation-cap',
  'envelope',
  'equal-circle',
  'minus',
  'folder-open',
  'venus',
  'mars',
  'estate',
  'info-circle',
  'columns',
  'english-to-chinese',
  'bag-alt',
  'chart-line',
  'map-marker-alt',
  'lock-alt',
  'flag', // (not unicons)
  'at',
  'user',
  'user-circle',
  'clipboard-check', // (not unicons, personal mashup)
  'building',
  'compass',
  'phone',
  'pin', // (not unicons)
  'microphone',
  'user-search', // (not unicons, personal mashup)
  'house-user',
  'star-solid',
  'star',
  'coins',
  'euro-circle',
  'file-search-alt',
  'question-circle',
  'gift',
  'birthday-cake', // (not unicons)
  'bunting-flags', // (not unicons)
  'tag-alt',
  'tablet',
  'mobile',
  'video',
  'plus-circle',
  'pen',
  'check-circle',
  'certified', // (not unicons, personal mashup)
  'plug',
] as const

export const player = [
  'play',
  'play_outline',
  'control_stop',
  'control_pause',
  'control_forward',
  'control_backward',
  'fullscreen_off',
  'fullscreen_on',
  'screenshare_off',
  'screenshare_on',
  'microphone_on',
  'microphone_off',
  'cast',
  'cast_connected',
  'cast_unavailable',
  'camera_on',
  'camera_off',
  'stop-circle-solid',
  'pause-circle-solid',
  'previous',
  'step-forward',
  'expand-arrows-alt',
  'compress-arrows',
  'screen-share', // (not unicons)
  'stop-screen-share', // (not unicons)
  'microphone',
  'microphone-slash',
  'cast', // (not unicons)
  'cast-connected', // (not unicons, personal mashup)
  'cast-unavailable', // (not unicons, personal mashup)
  'video',
  'video-slash',
  'airplay',
  'history',
  'playlist', // (not unicons)
  'volume-up',
  'volume-mute',
  'closed-captioning',
] as const

export const wtf = [
  'package',
  'basketball',
  'book',
  'book2',
  'bulb',
  'buoy',
  'calcul',
  'camera',
  'caddy',
  'clipboard',
  'coffee',
  'compass',
  'computer',
  'hard_hat',
  'credit_card',
  'crescent_moon',
  'crescent_moon_outline',
  'cross_target',
  'crown',
  'dish',
  'diamond',
  'factory',
  'fingerprint',
  'flag',
  'flag_outline',
  'gear',
  'handshake',
  'hashtag',
  'headset',
  'heart_shiny',
  'house',
  'justice_hammer',
  'key',
  'leaf',
  'map',
  'masonry',
  'masonry2',
  'megaphone',
  'mic',
  'microship',
  'money',
  'mountain',
  'music',
  'paperplane',
  'pencil',
  'pictures',
  'piechart',
  'pizza',
  'puzzle',
  'puzzle_outline',
  'shield',
  'spanner',
  'sparkles',
  'stackserver',
  'ruler',
  'desktop',
  'hard-hat',
  'credit-card',
  'moon-solid',
  'moon',
  'crosshair',
  'crown', // (not unicons)
  'restaurant',
  'diamond',
  'industry', // (not unicons)
  'fingerprint', // (not unicons)
  'flag',
  'flag-solid', // (not unicons, personal mashup)
  'setting',
  'handshake',
  'hashtag', // (not unicons)
  'headphones',
  'heart',
  'estate',
  'balance-scale',
  'key-skeleton',
  'leaf', // (not unicons)
  'map',
  'masonry', // (not unicons, personal mashup)
  'masonry-plus', // (not unicons, personal mashup)
  'megaphone',
  'microphone',
  'processor',
  'euro-circle',
  'mountains',
  'pen',
  'images',
  'chart-pie-alt',
  'pizza-slice',
  'puzzle-piece-solid',
  'puzzle-piece',
  'shield',
  'wrench',
  'sparkles', // (not unicons)
  'server',
  'sun',
  'hunting',
  'thumbs-up',
  'thumbs-down',
  'trees',
  'sofa', // (not unicons)
  'exit', // (not unicons, personal mashup)
  'redo',
  'play',
  'ban',
] as const

export const files = ['file', 'image'] as const

export const markdown = [
  'bold',
  'code',
  'code_block',
  'italic',
  'ordered_list',
  'unordered_list',
  'quote',
  'strikethrough',
  'heading',
  'heading_1',
  'heading_2',
  'heading_3',
  'heading_4',
  'heading_5',
  'heading_6',
  'type',
  'list-ol-alt',
  'list-ul',
  'quote', // (not unicons)
  'text-strike-through',
  'heading', // (not unicons, original creation)
  'heading-1', // (not unicons, original creation)
  'heading-2', // (not unicons, original creation)
  'heading-3', // (not unicons, original creation)
  'heading-4', // (not unicons, original creation)
  'heading-5', // (not unicons, original creation)
  'heading-6', // (not unicons, original creation)
  'font',
  'underline',
] as const

export const table = ['table', 'columns'] as const

export const brands = [
  'behance',
  'dribbble',
  'facebook',
  'github',
  'google',
  'instagram',
  'linkedin',
  'npm',
  'pinterest',
  'slack',
  'stackoverflow',
  'tiktok',
  'twitch',
  'x',
  'xing',
  'npm', // (not unicons)
  'pinterest', // (not unicons)
  'slack',
  'stackoverflow', // (not unicons)
  'tiktok',
  'twitch', // (not unicons)
  'x', // (not unicons)
  'xing', // (not unicons)
  'youtube',
  'zapier', // (not unicons)
] as const

export const welcome = ['symbol', 'wttj'] as const

export const flags = ['flag-fr', 'flag-en', 'flag-us'] as const

export const icons = [
  ...actions,
  ...arrows,
  ...brands,
  ...files,
  ...flags,
  ...markdown,
  ...miscellaneous,
  ...player,
  ...table,
  ...welcome,
  ...wtf,
] as const
