export const arrows = [
  'angle-left-b',
  'angle-right-b',
  'angle-up',
  'angle-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'left-arrow-to-left',
  'arrow-to-right',
  'top-arrow-to-top',
  'arrow-to-bottom',
] as const

export const actions = [
  'activity',
  'add',
  'archive',
  'aspect_ratio_fit',
  'aspect_ratio_fill',
  'bulk',
  'in_progress_candidate',
  'new_candidate',
  'refuse_candidate',
  'check',
  'times',
  'trash',
  'download',
  'upload',
  'drag_and_drop',
  'copy',
  'pen',
  'compress-arrows',
  'expand-arrows-alt',
  'text-size',
  'external-link-alt',
  'heart',
  'heart_outline',
  'filters',
  'show',
  'hide',
  'link',
  'log_out',
  'menu',
  'more_android',
  'more',
  'move',
  'notification',
  'print',
  'promote',
  'reset',
  'save',
  'search',
  'setting',
  'share-alt',
  'share',
] as const

export const miscellaneous = [
  'actions',
  'cover_letter',
  'details',
  'resume',
  'questions',
  'negative',
  'positive',
  'negative_outline',
  'positive_outline',
  'negative_straight',
  'positive_straight',
  'address',
  'alert',
  'alert_outline',
  'square_alert',
  'analytics',
  'attachment',
  'bar_chart',
  'burn',
  'candidate_status',
  'card_view',
  'trophy',
  'bookmark',
  'bookmark_outline',
  'clock',
  'comment',
  'comment_outline',
  'contract',
  'write',
  'date',
  'department',
  'earth',
  'education_level',
  'email',
  'email_outline',
  'equal',
  'remove',
  'folder',
  'female',
  'male',
  'home',
  'information',
  'information_outline',
  'kanban',
  'language',
  'suitcase',
  'line_chart',
  'location',
  'lock',
  'lock_rounded',
  'flag_pointed',
  'mention',
  'user-circle',
  'user',
  'user_outline',
  'offer_status',
  'office',
  'origine',
  'phone',
  'phone_outline',
  'pin',
  'podcast',
  'search_people',
  'remote',
  'review',
  'review_outline',
  'salary',
  'euro_currency',
  'source',
  'question',
  'anniversary',
  'birthday',
  'celebrate',
  'star',
  'star_outline',
  'tag',
  'tablet',
  'mobile',
  'video',
  'plus-circle',
  'edit',
  'check-circle',
  'award',
  'plug',
  'clock',
  'smile-beam-solid',
  'sad-solid',
  'music',
  'package',
  '10-plus-solid',
] as const

export const player = [
  'play',
  'play_outline',
  'control_stop',
  'control_pause',
  'control_forward',
  'control_backward',
  'fullscreen_off',
  'fullscreen_on',
  'screenshare_off',
  'screenshare_on',
  'microphone_on',
  'microphone_off',
  'cast',
  'cast_connected',
  'cast_unavailable',
  'camera_on',
  'camera_off',
  'airplay',
  'clock',
  'list-ul',
  'volume-up',
  'volume-mute',
  'closed-captioning',
] as const

export const wtf = [
  'basketball',
  'book',
  'book2',
  'bulb',
  'buoy',
  'calcul',
  'camera',
  'caddy',
  'clipboard',
  'coffee',
  'compass',
  'computer',
  'hard_hat',
  'credit_card',
  'crescent_moon',
  'crescent_moon_outline',
  'cross_target',
  'crown',
  'dish',
  'diamond',
  'factory',
  'fingerprint',
  'flag',
  'flag_outline',
  'gear',
  'handshake',
  'hashtag',
  'headset',
  'heart_shiny',
  'house',
  'justice_hammer',
  'key',
  'leaf',
  'map',
  'masonry',
  'masonry2',
  'megaphone',
  'mic',
  'microship',
  'money',
  'mountain',
  'music',
  'paperplane',
  'pencil',
  'pictures',
  'piechart',
  'pizza',
  'puzzle',
  'puzzle_outline',
  'shield',
  'spanner',
  'sparkles',
  'stackserver',
  'sun',
  'hunting',
  'thumbs-up',
  'thumbs-down',
  'triangle',
  'trees',
  'users',
  'presentation',
  'redo',
  'play',
  'ban',
] as const

export const files = ['file', 'image'] as const

export const markdown = [
  'bold',
  'code',
  'code_block',
  'italic',
  'ordered_list',
  'unordered_list',
  'quote',
  'strikethrough',
  'heading',
  'heading_1',
  'heading_2',
  'heading_3',
  'heading_4',
  'heading_5',
  'heading_6',
  'type',
  'underline',
] as const

export const table = ['table', 'columns', 'trash'] as const

export const brands = [
  'behance',
  'dribbble',
  'facebook',
  'github',
  'google',
  'instagram',
  'linkedin',
  'npm',
  'pinterest',
  'slack',
  'stackoverflow',
  'tiktok',
  'twitch',
  'x',
  'xing',
  'youtube',
] as const

export const welcome = ['symbol', 'wttj'] as const

export const flags = ['flag-fr', 'flag-en', 'flag-us'] as const

export const icons = [
  ...actions,
  ...arrows,
  ...brands,
  ...files,
  ...flags,
  ...markdown,
  ...miscellaneous,
  ...player,
  ...table,
  ...welcome,
  ...wtf,
] as const
