export const arrows = [
  'angle-left-b',
  'angle-right-b',
  'angle-up',
  'angle-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'left-arrow-to-left',
  'arrow-to-right',
  'top-arrow-to-top',
  'arrow-to-bottom',
] as const

export const actions = [
  'asterisk',
  'info-circle',
  'chart-line',
  'plus',
  'archive-alt',
  'arrows-shrink-h',
  'arrows-maximize',
  'apps',
  'user-check',
  'user-plus',
  'user-times',
  'check',
  'times',
  'trash',
  'import',
  'upload',
  'draggable-dots',
  'copy',
  'pen',
  'compress-arrows',
  'expand-arrows-alt',
  'text-size',
  'external-link-alt',
  'heart',
  'filter',
  'eye',
  'eye-slash',
  'link',
  'sign-out-alt',
  'bars',
  'ellipsis-v',
  'ellipsis-h',
  'arrows-resize',
  'bell',
  'print',
  'bolt-alt',
  'redo',
  'save',
  'search',
  'setting',
  'share-alt',
  'share',
] as const

export const miscellaneous = [
  'sparkles',
  'rocket',
  'file-alt',
  'user-square',
  'book-reader',
  'file-question-alt',
  'sad',
  'sign-right',
  'exclamation-triangle',
  'exclamation-circle',
  'exclamation-octagon',
  'chart-pie',
  'paperclip',
  'chart-bar',
  'fire',
  'user-check',
  'apps',
  'trophy',
  'bookmark',
  'clock',
  'comment-alt-lines',
  'file-edit-alt',
  'illustration',
  'calendar',
  'users-alt',
  'globe',
  'graduation-cap',
  'envelope',
  'equal-circle',
  'minus',
  'folder-open',
  'venus',
  'mars',
  'estate',
  'info-circle',
  'info-circle',
  'columns',
  'english-to-chinese',
  'bag-alt',
  'chart-line',
  'map-marker-alt',
  'lock-alt',
  'flag',
  'at',
  'user-circle',
  'clipboard-check',
  'building',
  'compass',
  'phone',
  'phone',
  'map-pin',
  'microphone',
  'users-search',
  'house-user',
  'start',
  'start',
  'dollar-sign',
  'euro-circle',
  'link',
  'question-circle',
  'calendar-alt',
  'gift',
  'party',
  'star',
  'tag-alt',
  'tablet',
  'mobile',
  'video',
  'plus-circle',
  'edit',
  'check-circle',
  'award',
  'plug',
  'clock',
  'smile-beam-solid',
  'sad-solid',
  'music',
  'package',
  '10-plus-solid',
] as const

export const player = [
  'play',
  'step-forward',
  'step-backward',
  'expand-arrows-alt',
  'compress-arrows',
  'desktop-slash',
  'desktop',
  'microphone',
  'microphone-slash',
  'tv-retro',
  'tv-retro-slash',
  'video',
  'video-slash',
  'airplay',
  'clock',
  'list-ul',
  'volume-up',
  'volume-mute',
  'closed-captioning',
] as const

export const wtf = [
  'basketball',
  'book-alt',
  'lightbulb-alt',
  'life-ring',
  'calculator-alt',
  'camera',
  'shopping-cart',
  'clipboard-notes',
  'coffee',
  'compass',
  'desktop',
  'hard-hat',
  'credit-card',
  'moon',
  'crosshairs',
  'crown',
  'restaurant',
  'diamond',
  'industry',
  'fingerprint',
  'flag',
  'setting',
  'handshake',
  'hashtag',
  'headphones',
  'heart-sign',
  'estate',
  'balance-scale',
  'key-skeleton',
  'leaf',
  'map',
  'th',
  'th-large',
  'megaphone',
  'microphone',
  'processor',
  'dollar-sign',
  'mountains',
  'message',
  'pen',
  'pictures',
  'piechart',
  'pizza-slice',
  'puzzle-piece',
  'shield',
  'wrench',
  'star',
  'server',
  'sun',
  'hunting',
  'thumbs-up',
  'thumbs-down',
  'triangle',
  'trees',
  'users',
  'presentation',
  'redo',
  'play',
  'ban',
] as const

export const files = ['file', 'image'] as const

export const markdown = [
  'bold',
  'arrow',
  'brackets-curly',
  'italic',
  'list-ol-alt',
  'list-ul',
  'quote-left',
  'text-strike-through',
  'text-size',
  'font',
  'underline',
] as const

export const table = ['table', 'columns', 'trash'] as const

export const brands = [
  'behance',
  'dribbble',
  'facebook',
  'github',
  'google',
  'instagram',
  'linkedin',
  'slack',
  'youtube',
] as const

export const welcome = ['symbol', 'wttj'] as const

export const flags = ['flag-fr', 'flag-en', 'flag-us'] as const

export const icons = [
  ...actions,
  ...arrows,
  ...brands,
  ...files,
  ...flags,
  ...markdown,
  ...miscellaneous,
  ...player,
  ...table,
  ...welcome,
  ...wtf,
] as const
