import type { IconProps } from './Icon.types'
export declare const ActionsIcon: IconProps
export declare const ActivityIcon: IconProps
export declare const AddIcon: IconProps
export declare const AddressIcon: IconProps
export declare const AirplayIcon: IconProps
export declare const AlertIcon: IconProps
export declare const AlertOutlineIcon: IconProps
export declare const AnalyticsIcon: IconProps
export declare const AnniversaryIcon: IconProps
export declare const ArchiveIcon: IconProps
export declare const ArrowDownIcon: IconProps
export declare const ArrowLeftIcon: IconProps
export declare const ArrowLineDownIcon: IconProps
export declare const ArrowLineLeftIcon: IconProps
export declare const ArrowLineRightIcon: IconProps
export declare const ArrowLineUpIcon: IconProps
export declare const ArrowRightIcon: IconProps
export declare const ArrowUpIcon: IconProps
export declare const AspectRatioFillIcon: IconProps
export declare const AspectRatioFitIcon: IconProps
export declare const AttachmentIcon: IconProps
export declare const AvatarIcon: IconProps
export declare const AvatarAccessoryIcon: IconProps
export declare const AvatarBodyIcon: IconProps
export declare const AvatarBottomIcon: IconProps
export declare const AvatarCostumeIcon: IconProps
export declare const AvatarHeadIcon: IconProps
export declare const AvatarTopIcon: IconProps
export declare const BarChartIcon: IconProps
export declare const BasketballIcon: IconProps
export declare const BehanceIcon: IconProps
export declare const BirthdayIcon: IconProps
export declare const BoldIcon: IconProps
export declare const BookIcon: IconProps
export declare const Book2Icon: IconProps
export declare const BookmarkIcon: IconProps
export declare const BookmarkOutlineIcon: IconProps
export declare const BulbIcon: IconProps
export declare const BulkIcon: IconProps
export declare const BuoyIcon: IconProps
export declare const BurnIcon: IconProps
export declare const CaddyIcon: IconProps
export declare const CalculIcon: IconProps
export declare const CameraIcon: IconProps
export declare const CameraOffIcon: IconProps
export declare const CameraOnIcon: IconProps
export declare const CandidateStatusIcon: IconProps
export declare const CardViewIcon: IconProps
export declare const CastIcon: IconProps
export declare const CastConnectedIcon: IconProps
export declare const CastUnavailableIcon: IconProps
export declare const CelebrateIcon: IconProps
export declare const CertifiedIcon: IconProps
export declare const CheckIcon: IconProps
export declare const ClipboardIcon: IconProps
export declare const ClockIcon: IconProps
export declare const CodeIcon: IconProps
export declare const CodeBlockIcon: IconProps
export declare const CoffeeIcon: IconProps
export declare const CollapseIcon: IconProps
export declare const CommentIcon: IconProps
export declare const CommentOutlineIcon: IconProps
export declare const CommonAreaIcon: IconProps
export declare const CompassIcon: IconProps
export declare const ComputerIcon: IconProps
export declare const ConnectionIcon: IconProps
export declare const ContractIcon: IconProps
export declare const ControlBackwardIcon: IconProps
export declare const ControlForwardIcon: IconProps
export declare const ControlPauseIcon: IconProps
export declare const ControlStopIcon: IconProps
export declare const CopyIcon: IconProps
export declare const CoverLetterIcon: IconProps
export declare const CreateIcon: IconProps
export declare const CreditCardIcon: IconProps
export declare const CrescentMoonIcon: IconProps
export declare const CrescentMoonOutlineIcon: IconProps
export declare const CrossIcon: IconProps
export declare const CrossTargetIcon: IconProps
export declare const CrownIcon: IconProps
export declare const CsvIcon: IconProps
export declare const DateIcon: IconProps
export declare const DepartmentIcon: IconProps
export declare const DetailsIcon: IconProps
export declare const DiamondIcon: IconProps
export declare const DishIcon: IconProps
export declare const DocIcon: IconProps
export declare const DocxIcon: IconProps
export declare const DownIcon: IconProps
export declare const DownloadIcon: IconProps
export declare const DragAndDropIcon: IconProps
export declare const DribbbleIcon: IconProps
export declare const EarthIcon: IconProps
export declare const EditIcon: IconProps
export declare const EducationLevelIcon: IconProps
export declare const EmailIcon: IconProps
export declare const EmailOutlineIcon: IconProps
export declare const EotIcon: IconProps
export declare const EqualIcon: IconProps
export declare const EuroCurrencyIcon: IconProps
export declare const ExpandIcon: IconProps
export declare const ExpandTextIcon: IconProps
export declare const ExtendIcon: IconProps
export declare const ExternalLinkIcon: IconProps
export declare const FacebookIcon: IconProps
export declare const FactoryIcon: IconProps
export declare const FemaleIcon: IconProps
export declare const FiltersIcon: IconProps
export declare const FingerprintIcon: IconProps
export declare const FlagIcon: IconProps
export declare const FlagCsIcon: IconProps
export declare const FlagEnIcon: IconProps
export declare const FlagEsIcon: IconProps
export declare const FlagFrIcon: IconProps
export declare const FlagOutlineIcon: IconProps
export declare const FlagPointedIcon: IconProps
export declare const FlagSkIcon: IconProps
export declare const FlagUsIcon: IconProps
export declare const FolderIcon: IconProps
export declare const FullscreenOffIcon: IconProps
export declare const FullscreenOnIcon: IconProps
export declare const GearIcon: IconProps
export declare const GifIcon: IconProps
export declare const GithubIcon: IconProps
export declare const GoogleIcon: IconProps
export declare const HandshakeIcon: IconProps
export declare const HardHatIcon: IconProps
export declare const HashtagIcon: IconProps
export declare const HeadingIcon: IconProps
export declare const Heading1Icon: IconProps
export declare const Heading2Icon: IconProps
export declare const Heading3Icon: IconProps
export declare const Heading4Icon: IconProps
export declare const Heading5Icon: IconProps
export declare const Heading6Icon: IconProps
export declare const HeadsetIcon: IconProps
export declare const HeartIcon: IconProps
export declare const HeartOutlineIcon: IconProps
export declare const HeartShinyIcon: IconProps
export declare const HideIcon: IconProps
export declare const HomeIcon: IconProps
export declare const HouseIcon: IconProps
export declare const InProgressCandidateIcon: IconProps
export declare const InformationIcon: IconProps
export declare const InformationOutlineIcon: IconProps
export declare const InstagramIcon: IconProps
export declare const ItalicIcon: IconProps
export declare const JpegIcon: IconProps
export declare const JpgIcon: IconProps
export declare const JusticeHammerIcon: IconProps
export declare const KanbanIcon: IconProps
export declare const KeyIcon: IconProps
export declare const LanguageIcon: IconProps
export declare const LeafIcon: IconProps
export declare const LeftIcon: IconProps
export declare const LineChartIcon: IconProps
export declare const LinkIcon: IconProps
export declare const LinkedinIcon: IconProps
export declare const LocationIcon: IconProps
export declare const LockIcon: IconProps
export declare const LockRoundedIcon: IconProps
export declare const LogOutIcon: IconProps
export declare const MaleIcon: IconProps
export declare const MapIcon: IconProps
export declare const MasonryIcon: IconProps
export declare const Masonry2Icon: IconProps
export declare const MeetingRoomIcon: IconProps
export declare const MegaphoneIcon: IconProps
export declare const MentionIcon: IconProps
export declare const MenuIcon: IconProps
export declare const MicIcon: IconProps
export declare const MicrophoneOffIcon: IconProps
export declare const MicrophoneOnIcon: IconProps
export declare const MicroshipIcon: IconProps
export declare const MobileIcon: IconProps
export declare const MoneyIcon: IconProps
export declare const MoreIcon: IconProps
export declare const MoreAndroidIcon: IconProps
export declare const MountainIcon: IconProps
export declare const MoveIcon: IconProps
export declare const MusicIcon: IconProps
export declare const NegativeIcon: IconProps
export declare const NegativeOutlineIcon: IconProps
export declare const NegativeStraightIcon: IconProps
export declare const NewCandidateIcon: IconProps
export declare const NotificationIcon: IconProps
export declare const NpmIcon: IconProps
export declare const OfferStatusIcon: IconProps
export declare const OfficeIcon: IconProps
export declare const OrderedListIcon: IconProps
export declare const OrigineIcon: IconProps
export declare const PaperplaneIcon: IconProps
export declare const PdfIcon: IconProps
export declare const PencilIcon: IconProps
export declare const PhoneIcon: IconProps
export declare const PhoneOutlineIcon: IconProps
export declare const PicturesIcon: IconProps
export declare const PiechartIcon: IconProps
export declare const PinIcon: IconProps
export declare const PinterestIcon: IconProps
export declare const PizzaIcon: IconProps
export declare const PlayIcon: IconProps
export declare const PlayOutlineIcon: IconProps
export declare const PlaylistIcon: IconProps
export declare const PngIcon: IconProps
export declare const PodcastIcon: IconProps
export declare const PositiveIcon: IconProps
export declare const PositiveOutlineIcon: IconProps
export declare const PositiveStraightIcon: IconProps
export declare const PptIcon: IconProps
export declare const PrintIcon: IconProps
export declare const PromoteIcon: IconProps
export declare const PuzzleIcon: IconProps
export declare const PuzzleOutlineIcon: IconProps
export declare const QuestionIcon: IconProps
export declare const QuestionsIcon: IconProps
export declare const QuoteIcon: IconProps
export declare const RefreshIcon: IconProps
export declare const RefuseCandidateIcon: IconProps
export declare const RemoteIcon: IconProps
export declare const RemoveIcon: IconProps
export declare const ResetIcon: IconProps
export declare const ResumeIcon: IconProps
export declare const ReviewIcon: IconProps
export declare const ReviewOutlineIcon: IconProps
export declare const RightIcon: IconProps
export declare const SalaryIcon: IconProps
export declare const SaveIcon: IconProps
export declare const ScreenshareOffIcon: IconProps
export declare const ScreenshareOnIcon: IconProps
export declare const SearchIcon: IconProps
export declare const SearchPeopleIcon: IconProps
export declare const SettingsIcon: IconProps
export declare const Share1Icon: IconProps
export declare const Share2Icon: IconProps
export declare const ShieldIcon: IconProps
export declare const ShowIcon: IconProps
export declare const SlackIcon: IconProps
export declare const SoundOffIcon: IconProps
export declare const SoundOnIcon: IconProps
export declare const SourceIcon: IconProps
export declare const SpannerIcon: IconProps
export declare const SparklesIcon: IconProps
export declare const SquareAlertIcon: IconProps
export declare const StackoverflowIcon: IconProps
export declare const StackserverIcon: IconProps
export declare const StarIcon: IconProps
export declare const StarOutlineIcon: IconProps
export declare const StrikethroughIcon: IconProps
export declare const SubtitleIcon: IconProps
export declare const SuccessIcon: IconProps
export declare const SuitcaseIcon: IconProps
export declare const SunIcon: IconProps
export declare const SvgIcon: IconProps
export declare const SymbolIcon: IconProps
export declare const TableIcon: IconProps
export declare const TableColumnAddAfterIcon: IconProps
export declare const TableColumnAddBeforeIcon: IconProps
export declare const TableColumnRemoveIcon: IconProps
export declare const TableDeleteIcon: IconProps
export declare const TableDivideIcon: IconProps
export declare const TableMergeCellsIcon: IconProps
export declare const TableRowAddAboveIcon: IconProps
export declare const TableRowAddBelowIcon: IconProps
export declare const TableRowRemoveIcon: IconProps
export declare const TabletIcon: IconProps
export declare const TagIcon: IconProps
export declare const TargetIcon: IconProps
export declare const TeepeeIcon: IconProps
export declare const ThumbDownIcon: IconProps
export declare const ThumbUpIcon: IconProps
export declare const ThunderclockIcon: IconProps
export declare const TiktokIcon: IconProps
export declare const TrashIcon: IconProps
export declare const TreeIcon: IconProps
export declare const TrophyIcon: IconProps
export declare const TtfIcon: IconProps
export declare const TwitchIcon: IconProps
export declare const TwitterIcon: IconProps
export declare const TxtIcon: IconProps
export declare const TypeIcon: IconProps
export declare const UnavailableIcon: IconProps
export declare const UnderlineIcon: IconProps
export declare const UnorderedListIcon: IconProps
export declare const UpIcon: IconProps
export declare const UpdateIcon: IconProps
export declare const UploadIcon: IconProps
export declare const UserIcon: IconProps
export declare const UserOutlineIcon: IconProps
export declare const VideoIcon: IconProps
export declare const VideoCameraIcon: IconProps
export declare const VideoCamera2Icon: IconProps
export declare const WatchLaterIcon: IconProps
export declare const WoffIcon: IconProps
export declare const Woff2Icon: IconProps
export declare const WriteIcon: IconProps
export declare const WttjIcon: IconProps
export declare const XIcon: IconProps
export declare const XingIcon: IconProps
export declare const XlsIcon: IconProps
export declare const XlsxIcon: IconProps
export declare const YoutubeIcon: IconProps
export declare const ZapierIcon: IconProps
export declare const ZipIcon: IconProps
