name: '[Design] 🔄 Update or feedback on existing component'
description: 'Request an update to improve foundations or existing component.'
labels: ['design', 'existing-component']
body:
  - type: 'markdown'
    attributes:
      value: |
        *Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately.
Thanks for contributing by creating this issue! ❤️*
  - type: dropdown
    id: components
    attributes:
      label: For which component?
      options:
        - Colours (Foundations)
        - Grids (Foundations)
        - Logos (Foundations)
        - Spacings (Foundations)
        - Typography (Foundations)
        - Accordion
        - Avatar
        - Badge
        - Breadcrumb
        - Button
        - Callout
        - Checkbox
        - Dropdown
        - Field
        - File drop
        - Growl
        - Hint
        - Icons
        - Illustrations
        - Link
        - Modal
        - Pagination
        - Radio Button
        - Select
        - Slider
        - Tabs
        - Tag
        - Textarea
        - Toast
        - Toggle
        - Tooltip
        - Others
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      placeholder: |
        Describe what you need and why you need to update this component/foundation.
    validations:
      required: true
  - type: 'input'
    id: 'due-date'
    attributes:
      label: 'Due Date'
      placeholder: 'DD/MM/YYYY'
    validations:
      required: true
