name: '[Design] 🫶 Component creation'
description: 'Request a new foundation or a new component.'
labels: ['design', 'component-creation']
body:
  - type: 'markdown'
    attributes:
      value: |
        ### Hi! 🙃

        Thanks for creating an issue 🫰!

        Have you before check others issues ?

        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately. 👍
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      placeholder: |
        Describe what you need and why you need to create this new component or foundation.
    validations:
      required: true
  - type: 'input'
    id: 'due-date'
    attributes:
      label: 'Due Date'
      placeholder: 'DD/MM/YYYY'
    validations:
      required: true
