name: '[Design] 🐛 Figma bug report'
description: 'Create a Figma bug report to improve Figma libraries.'
labels: ['design', 'figma-bug']
body:
  - type: 'markdown'
    attributes:
      value: |
        ### Hi! 🙃

        Thanks for creating an issue 🫰!

        Have you before check others issues ?

        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately. 👍
  - type: dropdown
    id: figma
    attributes:
      label: For which Figma library?
      options:
        - Basics
        - Data display
        - Dataviz palette - Categorical
        - Dataviz palette - Divergent
        - Dataviz palette - Sequential
        - Feedback
        - Forms
        - Icons
        - Illustrations
        - Navigation
    validations:
      required: true
  - type: dropdown
    id: components
    attributes:
      label: For which component?
      options:
        - Colours (Foundations)
        - Grids (Foundations)
        - Logos (Foundations)
        - Spacings (Foundations)
        - Typography (Foundations)
        - Accordion
        - Avatar
        - Badge
        - Breadcrumb
        - Button
        - Callout
        - Checkbox
        - Dropdown
        - Field
        - File drop
        - Growl
        - Hint
        - Icons
        - Illustrations
        - Link
        - Modal
        - Pagination
        - Radio Button
        - Select
        - Slider
        - Tabs
        - Tag
        - Textarea
        - Toast
        - Toggle
        - Tooltip
        - Others
    validations:
      required: true
  - type: 'textarea'
    id: 'current-behavior'
    attributes:
      label: 'Current Behavior'
      placeholder: |
        Describe the current behavior, this will help us to resolve the problem
    validations:
      required: true
  - type: 'textarea'
    id: 'expected-behavior'
    attributes:
      label: 'Expected Behavior'
      placeholder: |
        Describe the expected behavior, this will help us to resolve the problem
    validations:
      required: true
  - type: 'textarea'
    id: 'files'
    attributes:
      label: 'Screenshots / Videos'
      placeholder: |
        Upload screenshots or videos to describe the problem.
