name: '🔄 Update or feedback on existing component'
description: 'Request an update to improve foundations or existing component.'
labels: ['existing-component']
body:
  - type: 'markdown'
    attributes:
      value: |
        ### Hi! 🙃

        Thanks for creating an issue 🫰!

        Have you before check others issues ?

        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately. 👍
  - type: dropdown
    id: components
    attributes:
      label: For which component/foundations?
      options:
        - Colours
        - Grids
        - Logos
        - Spacings
        - Typography
        - Accordion
        - Alert
        - AspectRatio
        - Avatar
        - Badge
        - Box
        - Breadcrumb
        - Button
        - ButtonGroup
        - Callout
        - Card
        - Checkbox
        - DatePicker
        - DateTimePicker
        - Drawer
        - DropdownMenu
        - Emoji
        - EmojiPicker
        - Field
        - FileDrop
        - FileUpload
        - Flex
        - Grid
        - Hint
        - Icons
        - IconsFont
        - InputText
        - Label
        - Link
        - Loader
        - MarkdownEditor
        - Modal
        - Pagination
        - PasswordInput
        - Picker
        - Popover
        - RadioGroup
        - RadioTab
        - Search
        - Select
        - Shape
        - Slider
        - Stack
        - Swiper
        - Table
        - Tabs
        - Tag
        - Text
        - Textarea
        - TimePicker
        - Toast
        - Toggle
        - Tooltip
        - usecopyText
        - Others
    validations:
      required: true
  - type: dropdown
    id: prioritization
    attributes:
      label: Prioritization
      options:
        - Low 🏖️
        - Medium ⛰️
        - High 🌋
    validations:
      required: true
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      placeholder: |
        Describe what you need and why you need to update this component/foundation.
    validations:
      required: true
  - type: 'textarea'
    id: 'implementation'
    attributes:
      label: '[Tech] Implementation'
      description: 'If possible, describe how this feature could be implemented.'
      placeholder: 'See [CONTRIBUTING.mdx](https://github.com/WTTJ/welcome-ui/blob/main/CONTRIBUTING.mdx)'
  - type: 'input'
    id: 'due-date'
    attributes:
      label: 'Due Date'
      placeholder: 'DD/MM/YYYY'
