import React from 'react'
import { IconProps } from '@welcome-ui/icon'
export declare const ActionsIcon: React.FC<IconProps>
export declare const ActivityIcon: React.FC<IconProps>
export declare const AddIcon: React.FC<IconProps>
export declare const AddressIcon: React.FC<IconProps>
export declare const AirplayIcon: React.FC<IconProps>
export declare const AlertIcon: React.FC<IconProps>
export declare const AlertOutlineIcon: React.FC<IconProps>
export declare const AnalyticsIcon: React.FC<IconProps>
export declare const AnniversaryIcon: React.FC<IconProps>
export declare const ArchiveIcon: React.FC<IconProps>
export declare const ArrowDownIcon: React.FC<IconProps>
export declare const ArrowLeftIcon: React.FC<IconProps>
export declare const ArrowRightIcon: React.FC<IconProps>
export declare const ArrowUpIcon: React.FC<IconProps>
export declare const AspectRatioFillIcon: React.FC<IconProps>
export declare const AspectRatioFitIcon: React.FC<IconProps>
export declare const AttachmentIcon: React.FC<IconProps>
export declare const AvatarIcon: React.FC<IconProps>
export declare const AvatarAccessoryIcon: React.FC<IconProps>
export declare const AvatarBodyIcon: React.FC<IconProps>
export declare const AvatarBottomIcon: React.FC<IconProps>
export declare const AvatarCostumeIcon: React.FC<IconProps>
export declare const AvatarHeadIcon: React.FC<IconProps>
export declare const AvatarTopIcon: React.FC<IconProps>
export declare const BarChartIcon: React.FC<IconProps>
export declare const BasketballIcon: React.FC<IconProps>
export declare const BehanceIcon: React.FC<IconProps>
export declare const BirthdayIcon: React.FC<IconProps>
export declare const BoldIcon: React.FC<IconProps>
export declare const BookIcon: React.FC<IconProps>
export declare const Book2Icon: React.FC<IconProps>
export declare const BookmarkIcon: React.FC<IconProps>
export declare const BookmarkOutlineIcon: React.FC<IconProps>
export declare const BulbIcon: React.FC<IconProps>
export declare const BulkIcon: React.FC<IconProps>
export declare const BuoyIcon: React.FC<IconProps>
export declare const BurnIcon: React.FC<IconProps>
export declare const CaddyIcon: React.FC<IconProps>
export declare const CalculIcon: React.FC<IconProps>
export declare const CameraIcon: React.FC<IconProps>
export declare const CameraOffIcon: React.FC<IconProps>
export declare const CameraOnIcon: React.FC<IconProps>
export declare const CandidateStatusIcon: React.FC<IconProps>
export declare const CardViewIcon: React.FC<IconProps>
export declare const CastIcon: React.FC<IconProps>
export declare const CastConnectedIcon: React.FC<IconProps>
export declare const CastUnavailableIcon: React.FC<IconProps>
export declare const CelebrateIcon: React.FC<IconProps>
export declare const CheckIcon: React.FC<IconProps>
export declare const ClipboardIcon: React.FC<IconProps>
export declare const ClockIcon: React.FC<IconProps>
export declare const CodeIcon: React.FC<IconProps>
export declare const CodeBlockIcon: React.FC<IconProps>
export declare const CoffeeIcon: React.FC<IconProps>
export declare const CollapseIcon: React.FC<IconProps>
export declare const CommentIcon: React.FC<IconProps>
export declare const CommentOutlineIcon: React.FC<IconProps>
export declare const CommonAreaIcon: React.FC<IconProps>
export declare const CompassIcon: React.FC<IconProps>
export declare const ComputerIcon: React.FC<IconProps>
export declare const ContractIcon: React.FC<IconProps>
export declare const ControlBackwardIcon: React.FC<IconProps>
export declare const ControlForwardIcon: React.FC<IconProps>
export declare const ControlPauseIcon: React.FC<IconProps>
export declare const ControlStopIcon: React.FC<IconProps>
export declare const CopyIcon: React.FC<IconProps>
export declare const CoverLetterIcon: React.FC<IconProps>
export declare const CreateIcon: React.FC<IconProps>
export declare const CreditCardIcon: React.FC<IconProps>
export declare const CrescentMoonIcon: React.FC<IconProps>
export declare const CrescentMoonOutlineIcon: React.FC<IconProps>
export declare const CrossIcon: React.FC<IconProps>
export declare const CrossTargetIcon: React.FC<IconProps>
export declare const CrownIcon: React.FC<IconProps>
export declare const CsvIcon: React.FC<IconProps>
export declare const DateIcon: React.FC<IconProps>
export declare const DepartmentIcon: React.FC<IconProps>
export declare const DetailsIcon: React.FC<IconProps>
export declare const DiamondIcon: React.FC<IconProps>
export declare const DishIcon: React.FC<IconProps>
export declare const DocIcon: React.FC<IconProps>
export declare const DocxIcon: React.FC<IconProps>
export declare const DownIcon: React.FC<IconProps>
export declare const DownloadIcon: React.FC<IconProps>
export declare const DragAndDropIcon: React.FC<IconProps>
export declare const DribbbleIcon: React.FC<IconProps>
export declare const EarthIcon: React.FC<IconProps>
export declare const EditIcon: React.FC<IconProps>
export declare const EducationLevelIcon: React.FC<IconProps>
export declare const EmailIcon: React.FC<IconProps>
export declare const EmailOutlineIcon: React.FC<IconProps>
export declare const EotIcon: React.FC<IconProps>
export declare const EqualIcon: React.FC<IconProps>
export declare const EuroCurrencyIcon: React.FC<IconProps>
export declare const ExpandIcon: React.FC<IconProps>
export declare const ExpandTextIcon: React.FC<IconProps>
export declare const ExternalLinkIcon: React.FC<IconProps>
export declare const FacebookIcon: React.FC<IconProps>
export declare const FactoryIcon: React.FC<IconProps>
export declare const FemaleIcon: React.FC<IconProps>
export declare const FiltersIcon: React.FC<IconProps>
export declare const FingerprintIcon: React.FC<IconProps>
export declare const FlagIcon: React.FC<IconProps>
export declare const FlagCsIcon: React.FC<IconProps>
export declare const FlagEnIcon: React.FC<IconProps>
export declare const FlagEsIcon: React.FC<IconProps>
export declare const FlagFrIcon: React.FC<IconProps>
export declare const FlagOutlineIcon: React.FC<IconProps>
export declare const FlagPointedIcon: React.FC<IconProps>
export declare const FlagSkIcon: React.FC<IconProps>
export declare const FlagUsIcon: React.FC<IconProps>
export declare const FolderIcon: React.FC<IconProps>
export declare const FullscreenOffIcon: React.FC<IconProps>
export declare const FullscreenOnIcon: React.FC<IconProps>
export declare const GearIcon: React.FC<IconProps>
export declare const GifIcon: React.FC<IconProps>
export declare const GithubIcon: React.FC<IconProps>
export declare const GoogleIcon: React.FC<IconProps>
export declare const HandshakeIcon: React.FC<IconProps>
export declare const HardHatIcon: React.FC<IconProps>
export declare const HashtagIcon: React.FC<IconProps>
export declare const HeadingIcon: React.FC<IconProps>
export declare const Heading1Icon: React.FC<IconProps>
export declare const Heading2Icon: React.FC<IconProps>
export declare const Heading3Icon: React.FC<IconProps>
export declare const Heading4Icon: React.FC<IconProps>
export declare const Heading5Icon: React.FC<IconProps>
export declare const Heading6Icon: React.FC<IconProps>
export declare const HeadsetIcon: React.FC<IconProps>
export declare const HeartIcon: React.FC<IconProps>
export declare const HeartOutlineIcon: React.FC<IconProps>
export declare const HeartShinyIcon: React.FC<IconProps>
export declare const HideIcon: React.FC<IconProps>
export declare const HomeIcon: React.FC<IconProps>
export declare const HouseIcon: React.FC<IconProps>
export declare const InProgressCandidateIcon: React.FC<IconProps>
export declare const InformationIcon: React.FC<IconProps>
export declare const InformationOutlineIcon: React.FC<IconProps>
export declare const InstagramIcon: React.FC<IconProps>
export declare const ItalicIcon: React.FC<IconProps>
export declare const JpegIcon: React.FC<IconProps>
export declare const JpgIcon: React.FC<IconProps>
export declare const JusticeHammerIcon: React.FC<IconProps>
export declare const KanbanIcon: React.FC<IconProps>
export declare const KeyIcon: React.FC<IconProps>
export declare const LanguageIcon: React.FC<IconProps>
export declare const LeafIcon: React.FC<IconProps>
export declare const LeftIcon: React.FC<IconProps>
export declare const LineChartIcon: React.FC<IconProps>
export declare const LinkIcon: React.FC<IconProps>
export declare const LinkedinIcon: React.FC<IconProps>
export declare const LocationIcon: React.FC<IconProps>
export declare const LockIcon: React.FC<IconProps>
export declare const LockRoundedIcon: React.FC<IconProps>
export declare const LogOutIcon: React.FC<IconProps>
export declare const MaleIcon: React.FC<IconProps>
export declare const MapIcon: React.FC<IconProps>
export declare const MasonryIcon: React.FC<IconProps>
export declare const MeetingRoomIcon: React.FC<IconProps>
export declare const MegaphoneIcon: React.FC<IconProps>
export declare const MentionIcon: React.FC<IconProps>
export declare const MenuIcon: React.FC<IconProps>
export declare const MicIcon: React.FC<IconProps>
export declare const MicrophoneOffIcon: React.FC<IconProps>
export declare const MicrophoneOnIcon: React.FC<IconProps>
export declare const MicroshipIcon: React.FC<IconProps>
export declare const MoneyIcon: React.FC<IconProps>
export declare const MoreIcon: React.FC<IconProps>
export declare const MoreAndroidIcon: React.FC<IconProps>
export declare const MountainIcon: React.FC<IconProps>
export declare const MoveIcon: React.FC<IconProps>
export declare const MusicIcon: React.FC<IconProps>
export declare const NegativeIcon: React.FC<IconProps>
export declare const NegativeOutlineIcon: React.FC<IconProps>
export declare const NegativeStraightIcon: React.FC<IconProps>
export declare const NewCandidateIcon: React.FC<IconProps>
export declare const NotificationIcon: React.FC<IconProps>
export declare const NpmIcon: React.FC<IconProps>
export declare const OfferStatusIcon: React.FC<IconProps>
export declare const OfficeIcon: React.FC<IconProps>
export declare const OrderedListIcon: React.FC<IconProps>
export declare const OrigineIcon: React.FC<IconProps>
export declare const PaperplaneIcon: React.FC<IconProps>
export declare const PdfIcon: React.FC<IconProps>
export declare const PencilIcon: React.FC<IconProps>
export declare const PhoneIcon: React.FC<IconProps>
export declare const PhoneOutlineIcon: React.FC<IconProps>
export declare const PicturesIcon: React.FC<IconProps>
export declare const PiechartIcon: React.FC<IconProps>
export declare const PinIcon: React.FC<IconProps>
export declare const PinterestIcon: React.FC<IconProps>
export declare const PizzaIcon: React.FC<IconProps>
export declare const PlayIcon: React.FC<IconProps>
export declare const PlayOutlineIcon: React.FC<IconProps>
export declare const PlaylistIcon: React.FC<IconProps>
export declare const PngIcon: React.FC<IconProps>
export declare const PodcastIcon: React.FC<IconProps>
export declare const PositiveIcon: React.FC<IconProps>
export declare const PositiveOutlineIcon: React.FC<IconProps>
export declare const PositiveStraightIcon: React.FC<IconProps>
export declare const PptIcon: React.FC<IconProps>
export declare const PrintIcon: React.FC<IconProps>
export declare const PromoteIcon: React.FC<IconProps>
export declare const PuzzleIcon: React.FC<IconProps>
export declare const PuzzleOutlineIcon: React.FC<IconProps>
export declare const QuestionIcon: React.FC<IconProps>
export declare const QuestionsIcon: React.FC<IconProps>
export declare const QuoteIcon: React.FC<IconProps>
export declare const RefreshIcon: React.FC<IconProps>
export declare const RefuseCandidateIcon: React.FC<IconProps>
export declare const RemoteIcon: React.FC<IconProps>
export declare const RemoveIcon: React.FC<IconProps>
export declare const ResetIcon: React.FC<IconProps>
export declare const ResumeIcon: React.FC<IconProps>
export declare const ReviewIcon: React.FC<IconProps>
export declare const ReviewOutlineIcon: React.FC<IconProps>
export declare const RightIcon: React.FC<IconProps>
export declare const SalaryIcon: React.FC<IconProps>
export declare const SaveIcon: React.FC<IconProps>
export declare const ScreenshareOffIcon: React.FC<IconProps>
export declare const ScreenshareOnIcon: React.FC<IconProps>
export declare const SearchIcon: React.FC<IconProps>
export declare const SearchPeopleIcon: React.FC<IconProps>
export declare const SettingsIcon: React.FC<IconProps>
export declare const Share1Icon: React.FC<IconProps>
export declare const Share2Icon: React.FC<IconProps>
export declare const ShieldIcon: React.FC<IconProps>
export declare const ShowIcon: React.FC<IconProps>
export declare const SlackIcon: React.FC<IconProps>
export declare const SoundOffIcon: React.FC<IconProps>
export declare const SoundOnIcon: React.FC<IconProps>
export declare const SourceIcon: React.FC<IconProps>
export declare const SpannerIcon: React.FC<IconProps>
export declare const SparklesIcon: React.FC<IconProps>
export declare const SquareAlertIcon: React.FC<IconProps>
export declare const StackoverflowIcon: React.FC<IconProps>
export declare const StackserverIcon: React.FC<IconProps>
export declare const StarIcon: React.FC<IconProps>
export declare const StarOutlineIcon: React.FC<IconProps>
export declare const StrikethroughIcon: React.FC<IconProps>
export declare const SubtitleIcon: React.FC<IconProps>
export declare const SuccessIcon: React.FC<IconProps>
export declare const SuitcaseIcon: React.FC<IconProps>
export declare const SunIcon: React.FC<IconProps>
export declare const SvgIcon: React.FC<IconProps>
export declare const TableIcon: React.FC<IconProps>
export declare const TableColumnAddAfterIcon: React.FC<IconProps>
export declare const TableColumnAddBeforeIcon: React.FC<IconProps>
export declare const TableColumnRemoveIcon: React.FC<IconProps>
export declare const TableDeleteIcon: React.FC<IconProps>
export declare const TableDivideIcon: React.FC<IconProps>
export declare const TableMergeCellsIcon: React.FC<IconProps>
export declare const TableRowAddAboveIcon: React.FC<IconProps>
export declare const TableRowAddBelowIcon: React.FC<IconProps>
export declare const TableRowRemoveIcon: React.FC<IconProps>
export declare const TagIcon: React.FC<IconProps>
export declare const TargetIcon: React.FC<IconProps>
export declare const TeepeeIcon: React.FC<IconProps>
export declare const ThumbDownIcon: React.FC<IconProps>
export declare const ThumbUpIcon: React.FC<IconProps>
export declare const TiktokIcon: React.FC<IconProps>
export declare const TrashIcon: React.FC<IconProps>
export declare const TreeIcon: React.FC<IconProps>
export declare const TrophyIcon: React.FC<IconProps>
export declare const TtfIcon: React.FC<IconProps>
export declare const TwitchIcon: React.FC<IconProps>
export declare const TwitterIcon: React.FC<IconProps>
export declare const TxtIcon: React.FC<IconProps>
export declare const TypeIcon: React.FC<IconProps>
export declare const UnavailableIcon: React.FC<IconProps>
export declare const UnderlineIcon: React.FC<IconProps>
export declare const UnorderedListIcon: React.FC<IconProps>
export declare const UpIcon: React.FC<IconProps>
export declare const UpdateIcon: React.FC<IconProps>
export declare const UploadIcon: React.FC<IconProps>
export declare const UserIcon: React.FC<IconProps>
export declare const UserOutlineIcon: React.FC<IconProps>
export declare const VideoIcon: React.FC<IconProps>
export declare const VideoCameraIcon: React.FC<IconProps>
export declare const VideoCamera2Icon: React.FC<IconProps>
export declare const WatchLaterIcon: React.FC<IconProps>
export declare const WoffIcon: React.FC<IconProps>
export declare const Woff2Icon: React.FC<IconProps>
export declare const WriteIcon: React.FC<IconProps>
export declare const WttjIcon: React.FC<IconProps>
export declare const XIcon: React.FC<IconProps>
export declare const XingIcon: React.FC<IconProps>
export declare const XlsIcon: React.FC<IconProps>
export declare const XlsxIcon: React.FC<IconProps>
export declare const YoutubeIcon: React.FC<IconProps>
export declare const ZapierIcon: React.FC<IconProps>
export declare const ZipIcon: React.FC<IconProps>
