/* eslint-disable */
/** WARNING
This file is auto-generate with yarn watch command, do not change it directly!
**/

import dynamic from "next/dynamic";

export default {
  "/Accordion/docs/examples/avatar.tsx": dynamic(() => import("../../packages/Accordion/docs/examples/avatar.tsx").then(mod => mod), { ssr: false }),
  "/Accordion/docs/examples/open-at-start.tsx": dynamic(() => import("../../packages/Accordion/docs/examples/open-at-start.tsx").then(mod => mod), { ssr: false }),
  "/Accordion/docs/examples/overview.tsx": dynamic(() => import("../../packages/Accordion/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Accordion/docs/examples/with-custom-icon.tsx": dynamic(() => import("../../packages/Accordion/docs/examples/with-custom-icon.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/close-button.tsx": dynamic(() => import("../../packages/Alert/docs/examples/close-button.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/cta.tsx": dynamic(() => import("../../packages/Alert/docs/examples/cta.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/is-full-width.tsx": dynamic(() => import("../../packages/Alert/docs/examples/is-full-width.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/overview.tsx": dynamic(() => import("../../packages/Alert/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/sizes.tsx": dynamic(() => import("../../packages/Alert/docs/examples/sizes.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/title.tsx": dynamic(() => import("../../packages/Alert/docs/examples/title.tsx").then(mod => mod), { ssr: false }),
  "/Alert/docs/examples/variants.tsx": dynamic(() => import("../../packages/Alert/docs/examples/variants.tsx").then(mod => mod), { ssr: false }),
  "/AspectRatio/docs/examples/map.tsx": dynamic(() => import("../../packages/AspectRatio/docs/examples/map.tsx").then(mod => mod), { ssr: false }),
  "/AspectRatio/docs/examples/overview.tsx": dynamic(() => import("../../packages/AspectRatio/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/AspectRatio/docs/examples/ratio.tsx": dynamic(() => import("../../packages/AspectRatio/docs/examples/ratio.tsx").then(mod => mod), { ssr: false }),
  "/AspectRatio/docs/examples/video.tsx": dynamic(() => import("../../packages/AspectRatio/docs/examples/video.tsx").then(mod => mod), { ssr: false }),
  "/Avatar/docs/examples/images.tsx": dynamic(() => import("../../packages/Avatar/docs/examples/images.tsx").then(mod => mod), { ssr: false }),
  "/Avatar/docs/examples/overview.tsx": dynamic(() => import("../../packages/Avatar/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Avatar/docs/examples/shape.tsx": dynamic(() => import("../../packages/Avatar/docs/examples/shape.tsx").then(mod => mod), { ssr: false }),
  "/Avatar/docs/examples/texts.tsx": dynamic(() => import("../../packages/Avatar/docs/examples/texts.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/disabled.tsx": dynamic(() => import("../../packages/Badge/docs/examples/disabled.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/number-abbreviation.tsx": dynamic(() => import("../../packages/Badge/docs/examples/number-abbreviation.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/overview.tsx": dynamic(() => import("../../packages/Badge/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/shape.tsx": dynamic(() => import("../../packages/Badge/docs/examples/shape.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/size.tsx": dynamic(() => import("../../packages/Badge/docs/examples/size.tsx").then(mod => mod), { ssr: false }),
  "/Badge/docs/examples/variant.tsx": dynamic(() => import("../../packages/Badge/docs/examples/variant.tsx").then(mod => mod), { ssr: false }),
  "/Box/docs/examples/example.tsx": dynamic(() => import("../../packages/Box/docs/examples/example.tsx").then(mod => mod), { ssr: false }),
  "/Box/docs/examples/overview.tsx": dynamic(() => import("../../packages/Box/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Breadcrumb/docs/examples/child-disabled.tsx": dynamic(() => import("../../packages/Breadcrumb/docs/examples/child-disabled.tsx").then(mod => mod), { ssr: false }),
  "/Breadcrumb/docs/examples/last-child.tsx": dynamic(() => import("../../packages/Breadcrumb/docs/examples/last-child.tsx").then(mod => mod), { ssr: false }),
  "/Breadcrumb/docs/examples/overview.tsx": dynamic(() => import("../../packages/Breadcrumb/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Breadcrumb/docs/examples/separator.tsx": dynamic(() => import("../../packages/Breadcrumb/docs/examples/separator.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/disabled.tsx": dynamic(() => import("../../packages/Button/docs/examples/disabled.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/icons.tsx": dynamic(() => import("../../packages/Button/docs/examples/icons.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/link.tsx": dynamic(() => import("../../packages/Button/docs/examples/link.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/overview.tsx": dynamic(() => import("../../packages/Button/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/radius.tsx": dynamic(() => import("../../packages/Button/docs/examples/radius.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/shapes.tsx": dynamic(() => import("../../packages/Button/docs/examples/shapes.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/sizes.tsx": dynamic(() => import("../../packages/Button/docs/examples/sizes.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/variants-basics.tsx": dynamic(() => import("../../packages/Button/docs/examples/variants-basics.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/variants-states.tsx": dynamic(() => import("../../packages/Button/docs/examples/variants-states.tsx").then(mod => mod), { ssr: false }),
  "/Button/docs/examples/width.tsx": dynamic(() => import("../../packages/Button/docs/examples/width.tsx").then(mod => mod), { ssr: false }),
  "/ButtonGroup/docs/examples/overload.tsx": dynamic(() => import("../../packages/ButtonGroup/docs/examples/overload.tsx").then(mod => mod), { ssr: false }),
  "/ButtonGroup/docs/examples/overview.tsx": dynamic(() => import("../../packages/ButtonGroup/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Card/docs/examples/content.tsx": dynamic(() => import("../../packages/Card/docs/examples/content.tsx").then(mod => mod), { ssr: false }),
  "/Card/docs/examples/overview.tsx": dynamic(() => import("../../packages/Card/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Card/docs/examples/picture.tsx": dynamic(() => import("../../packages/Card/docs/examples/picture.tsx").then(mod => mod), { ssr: false }),
  "/Checkbox/docs/examples/hint.tsx": dynamic(() => import("../../packages/Checkbox/docs/examples/hint.tsx").then(mod => mod), { ssr: false }),
  "/Checkbox/docs/examples/labels.tsx": dynamic(() => import("../../packages/Checkbox/docs/examples/labels.tsx").then(mod => mod), { ssr: false }),
  "/Checkbox/docs/examples/nested.tsx": dynamic(() => import("../../packages/Checkbox/docs/examples/nested.tsx").then(mod => mod), { ssr: false }),
  "/Checkbox/docs/examples/overview.tsx": dynamic(() => import("../../packages/Checkbox/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Checkbox/docs/examples/variants.tsx": dynamic(() => import("../../packages/Checkbox/docs/examples/variants.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/icon.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/icon.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/months.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/months.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/overview.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/react-date-picker.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/react-date-picker.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/sizes.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/sizes.tsx").then(mod => mod), { ssr: false }),
  "/DatePicker/docs/examples/transparent.tsx": dynamic(() => import("../../packages/DatePicker/docs/examples/transparent.tsx").then(mod => mod), { ssr: false }),
  "/DateTimePicker/docs/examples/childs.tsx": dynamic(() => import("../../packages/DateTimePicker/docs/examples/childs.tsx").then(mod => mod), { ssr: false }),
  "/DateTimePicker/docs/examples/overview.tsx": dynamic(() => import("../../packages/DateTimePicker/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/DateTimePicker/docs/examples/sizes.tsx": dynamic(() => import("../../packages/DateTimePicker/docs/examples/sizes.tsx").then(mod => mod), { ssr: false }),
  "/DateTimePicker/docs/examples/transparent.tsx": dynamic(() => import("../../packages/DateTimePicker/docs/examples/transparent.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/backdrop.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/backdrop.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/layout.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/layout.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/overview.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/placement.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/placement.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/sizes.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/sizes.tsx").then(mod => mod), { ssr: false }),
  "/Drawer/docs/examples/styling.tsx": dynamic(() => import("../../packages/Drawer/docs/examples/styling.tsx").then(mod => mod), { ssr: false }),
  "/DropdownMenu/docs/examples/arrow.tsx": dynamic(() => import("../../packages/DropdownMenu/docs/examples/arrow.tsx").then(mod => mod), { ssr: false }),
  "/DropdownMenu/docs/examples/example.tsx": dynamic(() => import("../../packages/DropdownMenu/docs/examples/example.tsx").then(mod => mod), { ssr: false }),
  "/DropdownMenu/docs/examples/open.tsx": dynamic(() => import("../../packages/DropdownMenu/docs/examples/open.tsx").then(mod => mod), { ssr: false }),
  "/DropdownMenu/docs/examples/overview.tsx": dynamic(() => import("../../packages/DropdownMenu/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/disabled.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/disabled.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/image.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/image.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/no-type.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/no-type.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/others.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/others.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/overview.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/preview.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/preview.tsx").then(mod => mod), { ssr: false }),
  "/FileDrop/docs/examples/wordings.tsx": dynamic(() => import("../../packages/FileDrop/docs/examples/wordings.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/customize-button.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/customize-button.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/customize-preview-2.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/customize-preview-2.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/customize-preview.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/customize-preview.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/disabled.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/disabled.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/multiple.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/multiple.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/overview.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/overview.tsx").then(mod => mod), { ssr: false }),
  "/FileUpload/docs/examples/preview.tsx": dynamic(() => import("../../packages/FileUpload/docs/examples/preview.tsx").then(mod => mod), { ssr: false })
};
