/* eslint-disable perfectionist/sort-object-types */
/* eslint-disable perfectionist/sort-modules */
// UTILS

export type PolymorphicProps<E extends React.ElementType> = React.PropsWithChildren<
  React.ComponentPropsWithoutRef<E> & {
    as?: E
  }
>

export type ColorTokens = Extract<keyof ThemeVariables, `--color-${string}`>

export type ColorTokenNames = {
  [K in ColorTokens]: K extends `--${infer Rest}` ? Rest : never
}[ColorTokens]

export type ColorVariants = {
  [K in keyof ThemeVariables]: K extends `--color-${infer Rest}` ? Rest : never
}[keyof ThemeVariables]

export type ThemeVariables = {
  '--spacing': string
  '--spacing-0': string
  '--duration-fast': string
  '--duration-medium': string
  '--duration-slow': string
  '--timing-primary': string
  '--timing-secondary': string
  '--timing-tertiary': string
  '--components-colors-button-color-background-primary-main-default': string
  '--components-colors-button-color-background-primary-main-hover': string
  '--components-colors-button-color-background-primary-main-pressed': string
  '--components-colors-button-color-background-primary-main-disabled': string
  '--components-colors-button-color-background-primary-main-focused': string
  '--components-colors-button-color-background-primary-neutral-default': string
  '--components-colors-button-color-background-primary-neutral-hover': string
  '--components-colors-button-color-background-primary-neutral-pressed': string
  '--components-colors-button-color-background-primary-neutral-disabled': string
  '--components-colors-button-color-background-primary-neutral-focused': string
  '--components-colors-button-color-background-primary-danger-default': string
  '--components-colors-button-color-background-primary-danger-hover': string
  '--components-colors-button-color-background-primary-danger-pressed': string
  '--components-colors-button-color-background-primary-danger-disabled': string
  '--components-colors-button-color-background-primary-danger-focused': string
  '--components-colors-button-color-background-primary-ai-default': string
  '--components-colors-button-color-background-primary-ai-hover': string
  '--components-colors-button-color-background-primary-ai-pressed': string
  '--components-colors-button-color-background-primary-ai-disabled': string
  '--components-colors-button-color-background-primary-ai-focused': string
  '--components-colors-button-color-background-secondary-main-default': string
  '--components-colors-button-color-background-secondary-main-hover': string
  '--components-colors-button-color-background-secondary-main-pressed': string
  '--components-colors-button-color-background-secondary-main-disabled': string
  '--components-colors-button-color-background-secondary-main-focused': string
  '--components-colors-button-color-background-secondary-danger-default': string
  '--components-colors-button-color-background-secondary-danger-hover': string
  '--components-colors-button-color-background-secondary-danger-pressed': string
  '--components-colors-button-color-background-secondary-danger-disabled': string
  '--components-colors-button-color-background-secondary-danger-focused': string
  '--components-colors-button-color-background-tertiary-main-default': string
  '--components-colors-button-color-background-tertiary-main-hover': string
  '--components-colors-button-color-background-tertiary-main-pressed': string
  '--components-colors-button-color-background-tertiary-main-disabled': string
  '--components-colors-button-color-background-tertiary-main-focused': string
  '--components-colors-button-color-background-tertiary-danger-default': string
  '--components-colors-button-color-background-tertiary-danger-hover': string
  '--components-colors-button-color-background-tertiary-danger-pressed': string
  '--components-colors-button-color-background-tertiary-danger-disabled': string
  '--components-colors-button-color-background-tertiary-danger-focused': string
  '--components-colors-button-color-text-primary-main-default': string
  '--components-colors-button-color-text-primary-main-hover': string
  '--components-colors-button-color-text-primary-main-pressed': string
  '--components-colors-button-color-text-primary-main-disabled': string
  '--components-colors-button-color-text-primary-main-focused': string
  '--components-colors-button-color-text-primary-neutral-default': string
  '--components-colors-button-color-text-primary-neutral-hover': string
  '--components-colors-button-color-text-primary-neutral-pressed': string
  '--components-colors-button-color-text-primary-neutral-disabled': string
  '--components-colors-button-color-text-primary-neutral-focused': string
  '--components-colors-button-color-text-primary-danger-default': string
  '--components-colors-button-color-text-primary-danger-hover': string
  '--components-colors-button-color-text-primary-danger-pressed': string
  '--components-colors-button-color-text-primary-danger-disabled': string
  '--components-colors-button-color-text-primary-danger-focused': string
  '--components-colors-button-color-text-primary-ai-default': string
  '--components-colors-button-color-text-primary-ai-hover': string
  '--components-colors-button-color-text-primary-ai-pressed': string
  '--components-colors-button-color-text-primary-ai-disabled': string
  '--components-colors-button-color-text-primary-ai-focused': string
  '--components-colors-button-color-text-secondary-main-default': string
  '--components-colors-button-color-text-secondary-main-hover': string
  '--components-colors-button-color-text-secondary-main-pressed': string
  '--components-colors-button-color-text-secondary-main-disabled': string
  '--components-colors-button-color-text-secondary-main-focused': string
  '--components-colors-button-color-text-secondary-danger-default': string
  '--components-colors-button-color-text-secondary-danger-hover': string
  '--components-colors-button-color-text-secondary-danger-pressed': string
  '--components-colors-button-color-text-secondary-danger-disabled': string
  '--components-colors-button-color-text-secondary-danger-focused': string
  '--components-colors-button-color-text-tertiary-main-default': string
  '--components-colors-button-color-text-tertiary-main-hover': string
  '--components-colors-button-color-text-tertiary-main-pressed': string
  '--components-colors-button-color-text-tertiary-main-disabled': string
  '--components-colors-button-color-text-tertiary-main-focused': string
  '--components-colors-button-color-text-tertiary-danger-default': string
  '--components-colors-button-color-text-tertiary-danger-hover': string
  '--components-colors-button-color-text-tertiary-danger-pressed': string
  '--components-colors-button-color-text-tertiary-danger-disabled': string
  '--components-colors-button-color-text-tertiary-danger-focused': string
  '--components-colors-button-color-border-focused': string
  '--components-colors-button-color-border-secondary-main-default': string
  '--components-colors-button-color-border-secondary-main-hover': string
  '--components-colors-button-color-border-secondary-main-pressed': string
  '--components-colors-button-color-border-secondary-main-focused': string
  '--components-colors-button-color-border-secondary-danger-default': string
  '--components-colors-button-color-border-secondary-danger-hover': string
  '--components-colors-button-color-border-secondary-danger-pressed': string
  '--components-colors-button-color-border-secondary-danger-focused': string
  '--components-colors-button-color-icon-primary-main-default': string
  '--components-colors-button-color-icon-primary-main-hover': string
  '--components-colors-button-color-icon-primary-main-pressed': string
  '--components-colors-button-color-icon-primary-main-disabled': string
  '--components-colors-button-color-icon-primary-main-focused': string
  '--components-colors-button-color-icon-primary-neutral-default': string
  '--components-colors-button-color-icon-primary-neutral-hover': string
  '--components-colors-button-color-icon-primary-neutral-pressed': string
  '--components-colors-button-color-icon-primary-neutral-disabled': string
  '--components-colors-button-color-icon-primary-neutral-focused': string
  '--components-colors-button-color-icon-primary-danger-default': string
  '--components-colors-button-color-icon-primary-danger-hover': string
  '--components-colors-button-color-icon-primary-danger-pressed': string
  '--components-colors-button-color-icon-primary-danger-disabled': string
  '--components-colors-button-color-icon-primary-danger-focused': string
  '--components-colors-button-color-icon-primary-ai-default': string
  '--components-colors-button-color-icon-primary-ai-hover': string
  '--components-colors-button-color-icon-primary-ai-pressed': string
  '--components-colors-button-color-icon-primary-ai-disabled': string
  '--components-colors-button-color-icon-primary-ai-focused': string
  '--components-colors-button-color-icon-secondary-main-default': string
  '--components-colors-button-color-icon-secondary-main-hover': string
  '--components-colors-button-color-icon-secondary-main-pressed': string
  '--components-colors-button-color-icon-secondary-main-disabled': string
  '--components-colors-button-color-icon-secondary-main-focused': string
  '--components-colors-button-color-icon-secondary-danger-default': string
  '--components-colors-button-color-icon-secondary-danger-hover': string
  '--components-colors-button-color-icon-secondary-danger-pressed': string
  '--components-colors-button-color-icon-secondary-danger-disabled': string
  '--components-colors-button-color-icon-secondary-danger-focused': string
  '--components-colors-button-color-icon-tertiary-main-default': string
  '--components-colors-button-color-icon-tertiary-main-hover': string
  '--components-colors-button-color-icon-tertiary-main-pressed': string
  '--components-colors-button-color-icon-tertiary-main-disabled': string
  '--components-colors-button-color-icon-tertiary-main-focused': string
  '--components-colors-button-color-icon-tertiary-danger-default': string
  '--components-colors-button-color-icon-tertiary-danger-hover': string
  '--components-colors-button-color-icon-tertiary-danger-pressed': string
  '--components-colors-button-color-icon-tertiary-danger-disabled': string
  '--components-colors-button-color-icon-tertiary-danger-focused': string
  '--components-colors-link-color-background-primary-hover': string
  '--components-colors-link-color-background-primary-visited-default': string
  '--components-colors-link-color-background-primary-visited-hover': string
  '--components-colors-link-color-background-secondary-hover': string
  '--components-colors-link-color-background-secondary-visited-default': string
  '--components-colors-link-color-background-secondary-visited-hover': string
  '--components-colors-link-color-text-primary-default': string
  '--components-colors-link-color-text-primary-hover': string
  '--components-colors-link-color-text-primary-visited-default': string
  '--components-colors-link-color-text-primary-visited-hover': string
  '--components-colors-link-color-text-primary-disabled': string
  '--components-colors-link-color-text-secondary-default': string
  '--components-colors-link-color-text-secondary-hover': string
  '--components-colors-link-color-text-secondary-visited-default': string
  '--components-colors-link-color-text-secondary-visited-hover': string
  '--components-colors-link-color-text-secondary-disabled': string
  '--components-colors-link-color-icon-primary-default': string
  '--components-colors-link-color-icon-primary-hover': string
  '--components-colors-link-color-icon-primary-visited-default': string
  '--components-colors-link-color-icon-primary-visited-hover': string
  '--components-colors-link-color-icon-primary-disabled': string
  '--components-colors-link-color-icon-secondary-default': string
  '--components-colors-link-color-icon-secondary-hover': string
  '--components-colors-link-color-icon-secondary-visited-default': string
  '--components-colors-link-color-icon-secondary-visited-hover': string
  '--components-colors-link-color-icon-secondary-disabled': string
  '--components-colors-link-color-underline-primary-default': string
  '--components-colors-link-color-underline-primary-visited-default': string
  '--components-colors-link-color-underline-primary-visited-hover': string
  '--components-colors-link-color-underline-primary-disabled': string
  '--components-colors-link-color-underline-secondary-default': string
  '--components-colors-link-color-underline-secondary-visited-default': string
  '--components-colors-link-color-underline-secondary-visited-hover': string
  '--components-colors-link-color-underline-secondary-disabled': string
  '--components-colors-avatar-color-background-placeholder': string
  '--components-colors-avatar-color-background-initials-green': string
  '--components-colors-avatar-color-background-initials-teal': string
  '--components-colors-avatar-color-background-initials-blue': string
  '--components-colors-avatar-color-background-initials-violet': string
  '--components-colors-avatar-color-background-initials-pink': string
  '--components-colors-avatar-color-background-initials-orange': string
  '--components-colors-avatar-color-text-initials-green': string
  '--components-colors-avatar-color-text-initials-teal': string
  '--components-colors-avatar-color-text-initials-blue': string
  '--components-colors-avatar-color-text-initials-violet': string
  '--components-colors-avatar-color-text-initials-pink': string
  '--components-colors-avatar-color-text-initials-orange': string
  '--components-colors-avatar-color-icon-placeholder': string
  '--components-colors-badge-color-background-brand': string
  '--components-colors-badge-color-background-warm': string
  '--components-colors-badge-color-background-neutral': string
  '--components-colors-badge-color-background-blue': string
  '--components-colors-badge-color-text-brand': string
  '--components-colors-badge-color-text-warm': string
  '--components-colors-badge-color-text-neutral': string
  '--components-colors-badge-color-text-blue': string
  '--components-colors-card-action-dismiss-icon-default': string
  '--components-colors-card-action-dismiss-icon-hover': string
  '--components-colors-card-header-color-text-default': string
  '--components-colors-card-header-color-icon-default': string
  '--components-colors-card-body-meta-color-text-default': string
  '--components-colors-card-body-color-text-default': string
  '--components-colors-card-color-background-default': string
  '--components-colors-card-color-border-default': string
  '--components-colors-card-color-border-hover': string
  '--components-colors-card-color-icon-default': string
  '--components-colors-card-color-icon-hover': string
  '--components-colors-tag-color-background-brand-dark-default': string
  '--components-colors-tag-color-background-brand-dark-hover': string
  '--components-colors-tag-color-background-brand-dark-disabled': string
  '--components-colors-tag-color-background-brand-light-default': string
  '--components-colors-tag-color-background-brand-light-hover': string
  '--components-colors-tag-color-background-brand-light-disabled': string
  '--components-colors-tag-color-background-warm-dark-default': string
  '--components-colors-tag-color-background-warm-dark-hover': string
  '--components-colors-tag-color-background-warm-dark-disabled': string
  '--components-colors-tag-color-background-warm-light-default': string
  '--components-colors-tag-color-background-warm-light-hover': string
  '--components-colors-tag-color-background-warm-light-disabled': string
  '--components-colors-tag-color-background-green-dark-default': string
  '--components-colors-tag-color-background-green-dark-hover': string
  '--components-colors-tag-color-background-green-dark-disabled': string
  '--components-colors-tag-color-background-green-light-default': string
  '--components-colors-tag-color-background-green-light-hover': string
  '--components-colors-tag-color-background-green-light-disabled': string
  '--components-colors-tag-color-background-teal-dark-default': string
  '--components-colors-tag-color-background-teal-dark-hover': string
  '--components-colors-tag-color-background-teal-dark-disabled': string
  '--components-colors-tag-color-background-teal-light-default': string
  '--components-colors-tag-color-background-teal-light-hover': string
  '--components-colors-tag-color-background-teal-light-disabled': string
  '--components-colors-tag-color-background-blue-dark-default': string
  '--components-colors-tag-color-background-blue-dark-hover': string
  '--components-colors-tag-color-background-blue-dark-disabled': string
  '--components-colors-tag-color-background-blue-light-default': string
  '--components-colors-tag-color-background-blue-light-hover': string
  '--components-colors-tag-color-background-blue-light-disabled': string
  '--components-colors-tag-color-background-violet-dark-default': string
  '--components-colors-tag-color-background-violet-dark-hover': string
  '--components-colors-tag-color-background-violet-dark-disabled': string
  '--components-colors-tag-color-background-violet-light-default': string
  '--components-colors-tag-color-background-violet-light-hover': string
  '--components-colors-tag-color-background-violet-light-disabled': string
  '--components-colors-tag-color-background-pink-dark-default': string
  '--components-colors-tag-color-background-pink-dark-hover': string
  '--components-colors-tag-color-background-pink-dark-disabled': string
  '--components-colors-tag-color-background-pink-light-default': string
  '--components-colors-tag-color-background-pink-light-hover': string
  '--components-colors-tag-color-background-pink-light-disabled': string
  '--components-colors-tag-color-background-orange-dark-default': string
  '--components-colors-tag-color-background-orange-dark-hover': string
  '--components-colors-tag-color-background-orange-dark-disabled': string
  '--components-colors-tag-color-background-orange-light-default': string
  '--components-colors-tag-color-background-orange-light-hover': string
  '--components-colors-tag-color-background-orange-light-disabled': string
  '--components-colors-tag-color-background-red-dark-default': string
  '--components-colors-tag-color-background-red-dark-hover': string
  '--components-colors-tag-color-background-red-dark-disabled': string
  '--components-colors-tag-color-background-red-light-default': string
  '--components-colors-tag-color-background-red-light-hover': string
  '--components-colors-tag-color-background-red-light-disabled': string
  '--components-colors-tag-color-background-dash-default': string
  '--components-colors-tag-color-background-dash-hover': string
  '--components-colors-tag-color-background-dash-disabled': string
  '--components-colors-tag-color-background-ai-default': string
  '--components-colors-tag-color-background-ai-hover': string
  '--components-colors-tag-color-background-ai-disabled': string
  '--components-colors-tag-color-text-brand-dark-default': string
  '--components-colors-tag-color-text-brand-dark-hover': string
  '--components-colors-tag-color-text-brand-dark-disabled': string
  '--components-colors-tag-color-text-brand-light-default': string
  '--components-colors-tag-color-text-brand-light-hover': string
  '--components-colors-tag-color-text-brand-light-disabled': string
  '--components-colors-tag-color-text-warm-dark-default': string
  '--components-colors-tag-color-text-warm-dark-hover': string
  '--components-colors-tag-color-text-warm-dark-disabled': string
  '--components-colors-tag-color-text-warm-light-default': string
  '--components-colors-tag-color-text-warm-light-hover': string
  '--components-colors-tag-color-text-warm-light-disabled': string
  '--components-colors-tag-color-text-green-dark-default': string
  '--components-colors-tag-color-text-green-dark-disabled': string
  '--components-colors-tag-color-text-green-light-default': string
  '--components-colors-tag-color-text-green-light-disabled': string
  '--components-colors-tag-color-text-teal-dark-default': string
  '--components-colors-tag-color-text-teal-dark-hover': string
  '--components-colors-tag-color-text-teal-dark-disabled': string
  '--components-colors-tag-color-text-teal-light-default': string
  '--components-colors-tag-color-text-teal-light-hover': string
  '--components-colors-tag-color-text-teal-light-disabled': string
  '--components-colors-tag-color-text-blue-dark-default': string
  '--components-colors-tag-color-text-blue-dark-hover': string
  '--components-colors-tag-color-text-blue-dark-disabled': string
  '--components-colors-tag-color-text-blue-light-default': string
  '--components-colors-tag-color-text-blue-light-hover': string
  '--components-colors-tag-color-text-blue-light-disabled': string
  '--components-colors-tag-color-text-violet-dark-default': string
  '--components-colors-tag-color-text-violet-dark-hover': string
  '--components-colors-tag-color-text-violet-dark-disabled': string
  '--components-colors-tag-color-text-violet-light-default': string
  '--components-colors-tag-color-text-violet-light-hover': string
  '--components-colors-tag-color-text-violet-light-disabled': string
  '--components-colors-tag-color-text-pink-dark-default': string
  '--components-colors-tag-color-text-pink-dark-hover': string
  '--components-colors-tag-color-text-pink-dark-disabled': string
  '--components-colors-tag-color-text-pink-light-default': string
  '--components-colors-tag-color-text-pink-light-hover': string
  '--components-colors-tag-color-text-pink-light-disabled': string
  '--components-colors-tag-color-text-orange-dark-default': string
  '--components-colors-tag-color-text-orange-dark-hover': string
  '--components-colors-tag-color-text-orange-dark-disabled': string
  '--components-colors-tag-color-text-orange-light-default': string
  '--components-colors-tag-color-text-orange-light-hover': string
  '--components-colors-tag-color-text-orange-light-disabled': string
  '--components-colors-tag-color-text-red-dark-default': string
  '--components-colors-tag-color-text-red-dark-hover': string
  '--components-colors-tag-color-text-red-dark-disabled': string
  '--components-colors-tag-color-text-red-light-default': string
  '--components-colors-tag-color-text-red-light-hover': string
  '--components-colors-tag-color-text-red-light-disabled': string
  '--components-colors-tag-color-text-dash-default': string
  '--components-colors-tag-color-text-dash-hover': string
  '--components-colors-tag-color-text-dash-disabled': string
  '--components-colors-tag-color-text-ai-default': string
  '--components-colors-tag-color-text-ai-hover': string
  '--components-colors-tag-color-text-ai-disabled': string
  '--components-colors-tag-color-border-default': string
  '--components-colors-tag-color-border-dash-default': string
  '--components-colors-tag-color-border-dash-hover': string
  '--components-colors-tag-color-border-dash-disabled': string
  '--components-colors-tag-color-icon-brand-dark-default': string
  '--components-colors-tag-color-icon-brand-dark-hover': string
  '--components-colors-tag-color-icon-brand-dark-disabled': string
  '--components-colors-tag-color-icon-brand-light-default': string
  '--components-colors-tag-color-icon-brand-light-hover': string
  '--components-colors-tag-color-icon-brand-light-disabled': string
  '--components-colors-tag-color-icon-warm-dark-default': string
  '--components-colors-tag-color-icon-warm-dark-hover': string
  '--components-colors-tag-color-icon-warm-dark-disabled': string
  '--components-colors-tag-color-icon-warm-light-default': string
  '--components-colors-tag-color-icon-warm-light-hover': string
  '--components-colors-tag-color-icon-warm-light-disabled': string
  '--components-colors-tag-color-icon-green-dark-default': string
  '--components-colors-tag-color-icon-green-dark-disabled': string
  '--components-colors-tag-color-icon-green-light-default': string
  '--components-colors-tag-color-icon-green-light-disabled': string
  '--components-colors-tag-color-icon-teal-dark-default': string
  '--components-colors-tag-color-icon-teal-dark-hover': string
  '--components-colors-tag-color-icon-teal-dark-disabled': string
  '--components-colors-tag-color-icon-teal-light-default': string
  '--components-colors-tag-color-icon-teal-light-hover': string
  '--components-colors-tag-color-icon-teal-light-disabled': string
  '--components-colors-tag-color-icon-blue-dark-default': string
  '--components-colors-tag-color-icon-blue-dark-hover': string
  '--components-colors-tag-color-icon-blue-dark-disabled': string
  '--components-colors-tag-color-icon-blue-light-default': string
  '--components-colors-tag-color-icon-blue-light-hover': string
  '--components-colors-tag-color-icon-blue-light-disabled': string
  '--components-colors-tag-color-icon-violet-dark-default': string
  '--components-colors-tag-color-icon-violet-dark-hover': string
  '--components-colors-tag-color-icon-violet-dark-disabled': string
  '--components-colors-tag-color-icon-violet-light-default': string
  '--components-colors-tag-color-icon-violet-light-hover': string
  '--components-colors-tag-color-icon-violet-light-disabled': string
  '--components-colors-tag-color-icon-pink-dark-default': string
  '--components-colors-tag-color-icon-pink-dark-hover': string
  '--components-colors-tag-color-icon-pink-dark-disabled': string
  '--components-colors-tag-color-icon-pink-light-default': string
  '--components-colors-tag-color-icon-pink-light-hover': string
  '--components-colors-tag-color-icon-pink-light-disabled': string
  '--components-colors-tag-color-icon-orange-dark-default': string
  '--components-colors-tag-color-icon-orange-dark-hover': string
  '--components-colors-tag-color-icon-orange-dark-disabled': string
  '--components-colors-tag-color-icon-orange-light-default': string
  '--components-colors-tag-color-icon-orange-light-hover': string
  '--components-colors-tag-color-icon-orange-light-disabled': string
  '--components-colors-tag-color-icon-red-dark-default': string
  '--components-colors-tag-color-icon-red-dark-hover': string
  '--components-colors-tag-color-icon-red-dark-disabled': string
  '--components-colors-tag-color-icon-red-light-default': string
  '--components-colors-tag-color-icon-red-light-hover': string
  '--components-colors-tag-color-icon-red-light-disabled': string
  '--components-colors-tag-color-icon-dash-default': string
  '--components-colors-tag-color-icon-dash-hover': string
  '--components-colors-tag-color-icon-dash-disabled': string
  '--components-colors-tag-color-icon-ai-default': string
  '--components-colors-tag-color-icon-ai-hover': string
  '--components-colors-tag-color-icon-ai-disabled': string
  '--components-colors-window-header-action-color-background-common-default': string
  '--components-colors-window-header-action-color-background-common-hover': string
  '--components-colors-window-header-action-color-background-common-pressed': string
  '--components-colors-window-header-action-color-background-close-default': string
  '--components-colors-window-header-action-color-background-close-hover': string
  '--components-colors-window-header-action-color-background-close-pressed': string
  '--components-colors-window-header-action-color-border-close-default': string
  '--components-colors-window-header-action-color-icon-common-default': string
  '--components-colors-window-header-action-color-icon-common-hover': string
  '--components-colors-window-header-action-color-icon-common-pressed': string
  '--components-colors-window-header-action-color-icon-close-default': string
  '--components-colors-window-header-action-color-icon-close-hover': string
  '--components-colors-window-header-action-color-icon-close-pressed': string
  '--components-colors-window-header-color-background': string
  '--components-colors-window-header-color-text-default': string
  '--components-colors-window-header-tab-color-background-default': string
  '--components-colors-window-header-tab-color-background-hover': string
  '--components-colors-window-header-tab-color-background-active': string
  '--components-colors-window-header-tab-color-text-default': string
  '--components-colors-window-header-tab-color-text-hover': string
  '--components-colors-window-header-tab-color-text-active': string
  '--components-colors-window-header-tab-color-icon-default': string
  '--components-colors-window-header-tab-color-icon-hover': string
  '--components-colors-window-header-tab-color-icon-active': string
  '--components-colors-window-header-tab-color-border-default': string
  '--components-colors-window-body-color-background-default': string
  '--components-colors-window-color-border-default': string
  '--components-colors-window-color-border-hover': string
  '--components-colors-dropdown-menu-item-color-background-default': string
  '--components-colors-dropdown-menu-item-color-background-hover': string
  '--components-colors-dropdown-menu-item-color-background-disabled': string
  '--components-colors-dropdown-menu-item-color-text': string
  '--components-colors-dropdown-menu-item-color-icon-default': string
  '--components-colors-dropdown-menu-item-color-icon-hover': string
  '--components-colors-dropdown-menu-item-color-icon-disabled': string
  '--components-colors-dropdown-menu-color-background-default': string
  '--components-colors-dropdown-menu-color-border-default': string
  '--components-colors-latency-color-background-progress': string
  '--components-colors-latency-color-background-bar': string
  '--components-colors-callout-icon-color-background-brand': string
  '--components-colors-callout-icon-color-background-information': string
  '--components-colors-callout-icon-color-background-warning': string
  '--components-colors-callout-icon-color-background-danger': string
  '--components-colors-callout-icon-color-background-success': string
  '--components-colors-callout-icon-color-icon-brand': string
  '--components-colors-callout-icon-color-icon-information': string
  '--components-colors-callout-icon-color-icon-warning': string
  '--components-colors-callout-icon-color-icon-danger': string
  '--components-colors-callout-icon-color-icon-success': string
  '--components-colors-callout-icon-color-icon-ai': string
  '--components-colors-callout-color-background-brand': string
  '--components-colors-callout-color-background-information': string
  '--components-colors-callout-color-background-success': string
  '--components-colors-callout-color-background-warning': string
  '--components-colors-callout-color-background-danger': string
  '--components-colors-callout-color-background-ai': string
  '--components-colors-callout-color-text-brand-title': string
  '--components-colors-callout-color-text-brand-body': string
  '--components-colors-callout-color-text-information-title': string
  '--components-colors-callout-color-text-information-body': string
  '--components-colors-callout-color-text-success-title': string
  '--components-colors-callout-color-text-success-body': string
  '--components-colors-callout-color-text-warning-title': string
  '--components-colors-callout-color-text-warning-body': string
  '--components-colors-callout-color-text-danger-title': string
  '--components-colors-callout-color-text-danger-body': string
  '--components-colors-callout-color-text-ai-title': string
  '--components-colors-callout-color-text-ai-body': string
  '--components-colors-growl-icon-color-background-information': string
  '--components-colors-growl-icon-color-background-success': string
  '--components-colors-growl-icon-color-background-warning': string
  '--components-colors-growl-icon-color-background-error': string
  '--components-colors-growl-icon-color-icon-information': string
  '--components-colors-growl-icon-color-icon-warning': string
  '--components-colors-growl-icon-color-icon-error': string
  '--components-colors-growl-icon-color-icon-success': string
  '--components-colors-growl-color-background-default': string
  '--components-colors-growl-color-text-title': string
  '--components-colors-growl-color-text-body': string
  '--components-colors-growl-color-border-default': string
  '--components-colors-growl-color-border-hover': string
  '--components-colors-growl-color-icon-default': string
  '--components-colors-growl-color-icon-hover': string
  '--components-colors-tooltip-color-background': string
  '--components-colors-tooltip-color-border': string
  '--components-colors-tooltip-color-text': string
  '--components-colors-sticky-note-icon-color-background-brand': string
  '--components-colors-sticky-note-icon-color-background-green': string
  '--components-colors-sticky-note-icon-color-background-teal': string
  '--components-colors-sticky-note-icon-color-background-blue': string
  '--components-colors-sticky-note-icon-color-background-violet': string
  '--components-colors-sticky-note-icon-color-background-pink': string
  '--components-colors-sticky-note-icon-color-background-orange': string
  '--components-colors-sticky-note-icon-color-icon-brand': string
  '--components-colors-sticky-note-icon-color-icon-green': string
  '--components-colors-sticky-note-icon-color-icon-teal': string
  '--components-colors-sticky-note-icon-color-icon-blue': string
  '--components-colors-sticky-note-icon-color-icon-violet': string
  '--components-colors-sticky-note-icon-color-icon-pink': string
  '--components-colors-sticky-note-icon-color-icon-orange': string
  '--components-colors-sticky-note-color-background-brand': string
  '--components-colors-sticky-note-color-background-green': string
  '--components-colors-sticky-note-color-background-teal': string
  '--components-colors-sticky-note-color-background-blue': string
  '--components-colors-sticky-note-color-background-violet': string
  '--components-colors-sticky-note-color-background-pink': string
  '--components-colors-sticky-note-color-background-orange': string
  '--components-colors-sticky-note-color-border-default': string
  '--components-colors-sticky-note-color-text-body-brand': string
  '--components-colors-sticky-note-color-text-body-green': string
  '--components-colors-sticky-note-color-text-body-teal': string
  '--components-colors-sticky-note-color-text-body-blue': string
  '--components-colors-sticky-note-color-text-body-violet': string
  '--components-colors-sticky-note-color-text-body-pink': string
  '--components-colors-sticky-note-color-text-body-orange': string
  '--components-colors-sticky-note-color-text-title': string
  '--components-colors-toast-icon-color-background-information': string
  '--components-colors-toast-icon-color-background-success': string
  '--components-colors-toast-icon-color-background-warning': string
  '--components-colors-toast-icon-color-background-error': string
  '--components-colors-toast-icon-color-icon-information': string
  '--components-colors-toast-icon-color-icon-warning': string
  '--components-colors-toast-icon-color-icon-error': string
  '--components-colors-toast-icon-color-icon-success': string
  '--components-colors-toast-color-background-default': string
  '--components-colors-toast-color-text-body': string
  '--components-colors-toast-color-border-default': string
  '--components-colors-toast-color-border-hover': string
  '--components-colors-label-color-text-default': string
  '--components-colors-label-color-icon-default': string
  '--components-colors-label-color-icon-warning': string
  '--components-colors-label-color-icon-error': string
  '--components-colors-label-color-icon-success': string
  '--components-colors-label-color-icon-required': string
  '--components-colors-hint-color-text-default': string
  '--components-colors-hint-color-text-warning': string
  '--components-colors-hint-color-text-error': string
  '--components-colors-hint-color-text-success': string
  '--components-colors-input-password-strenght-color-background-default': string
  '--components-colors-input-password-strenght-color-background-too-weak': string
  '--components-colors-input-password-strenght-color-background-weak': string
  '--components-colors-input-password-strenght-color-background-good': string
  '--components-colors-input-password-strenght-color-background-strong': string
  '--components-colors-input-color-background-default': string
  '--components-colors-input-color-background-disabled': string
  '--components-colors-input-color-background-transparent': string
  '--components-colors-input-color-text-default': string
  '--components-colors-input-color-text-placeholder': string
  '--components-colors-input-color-text-disabled': string
  '--components-colors-input-color-border-default': string
  '--components-colors-input-color-border-hover': string
  '--components-colors-input-color-border-hover-transparent': string
  '--components-colors-input-color-border-active': string
  '--components-colors-input-color-border-success': string
  '--components-colors-input-color-border-warning': string
  '--components-colors-input-color-border-error': string
  '--components-colors-input-color-border-disabled': string
  '--components-colors-input-color-border-focused': string
  '--components-colors-input-color-icon-default': string
  '--components-colors-input-color-icon-placeholder': string
  '--components-colors-input-color-icon-disabled': string
  '--components-colors-checkbox-color-background-disabled': string
  '--components-colors-checkbox-color-background-unchecked-default': string
  '--components-colors-checkbox-color-background-checked-default': string
  '--components-colors-checkbox-color-background-checked-hover': string
  '--components-colors-checkbox-color-border-focused': string
  '--components-colors-checkbox-color-border-error': string
  '--components-colors-checkbox-color-border-disabled': string
  '--components-colors-checkbox-color-border-unchecked-default': string
  '--components-colors-checkbox-color-border-unchecked-hover': string
  '--components-colors-checkbox-color-icon-default': string
  '--components-colors-checkbox-color-icon-disabled': string
  '--components-colors-radio-indicator-color-background-default': string
  '--components-colors-radio-indicator-color-background-hover': string
  '--components-colors-radio-indicator-color-background-disabled': string
  '--components-colors-radio-color-border-focused': string
  '--components-colors-radio-color-border-unchecked-default': string
  '--components-colors-radio-color-border-unchecked-hover': string
  '--components-colors-radio-color-border-unchecked-disabled': string
  '--components-colors-radio-color-border-checked-default': string
  '--components-colors-radio-color-border-checked-hover': string
  '--components-colors-radio-color-border-checked-disabled': string
  '--components-colors-radio-color-background-unchecked-default': string
  '--components-colors-radio-color-background-unchecked-disabled': string
  '--components-colors-radio-color-background-checked-default': string
  '--components-colors-radio-color-background-checked-disabled': string
  '--components-colors-toggle-thumb-color-background-default': string
  '--components-colors-toggle-thumb-color-background-hover': string
  '--components-colors-toggle-thumb-color-background-disabled': string
  '--components-colors-toggle-thumb-color-border-default': string
  '--components-colors-toggle-thumb-color-border-hover': string
  '--components-colors-toggle-track-color-background-disabled': string
  '--components-colors-toggle-track-color-background-unchecked-default': string
  '--components-colors-toggle-track-color-background-checked-default': string
  '--components-colors-toggle-track-color-background-checked-hover': string
  '--components-colors-toggle-track-color-border-focused': string
  '--components-colors-toggle-track-color-border-unchecked-default': string
  '--components-colors-toggle-track-color-border-unchecked-hover': string
  '--components-colors-toggle-track-color-border-disabled': string
  '--components-colors-toggle-track-color-border-checked-default': string
  '--components-colors-toggle-track-color-border-checked-hover': string
  '--components-colors-toggle-track-color-icon-default': string
  '--components-colors-toggle-track-color-icon-hover': string
  '--components-colors-toggle-track-color-icon-disabled': string
  '--components-colors-breadcrumb-color-text-default': string
  '--components-colors-breadcrumb-color-text-hover': string
  '--components-colors-breadcrumb-color-text-active': string
  '--components-colors-breadcrumb-color-icon-default': string
  '--components-colors-breadcrumb-color-icon-hover': string
  '--components-colors-breadcrumb-color-icon-active': string
  '--components-colors-stepper-step-color-background-unchecked-default': string
  '--components-colors-stepper-step-color-background-unchecked-hover': string
  '--components-colors-stepper-step-color-background-checked-default': string
  '--components-colors-stepper-step-color-background-checked-hover': string
  '--components-colors-stepper-step-color-text-unchecked-default': string
  '--components-colors-stepper-step-color-text-unchecked-hover': string
  '--components-colors-stepper-step-color-text-checked-default': string
  '--components-colors-stepper-step-color-text-checked-hover': string
  '--components-colors-stepper-step-color-icon-unchecked-default': string
  '--components-colors-stepper-step-color-icon-unchecked-hover': string
  '--components-colors-stepper-step-color-icon-checked-default': string
  '--components-colors-stepper-step-color-icon-checked-hover': string
  '--components-colors-stepper-step-color-icon-success': string
  '--components-colors-stepper-step-color-border-checked-default': string
  '--components-colors-stepper-step-color-border-checked-hover': string
  '--components-colors-stepper-color-background': string
  '--components-colors-stepper-color-border-default': string
  '--components-colors-stepper-color-border-hover': string
  '--components-colors-stepper-color-icon-default': string
  '--components-colors-tab-color-background-unchecked-default': string
  '--components-colors-tab-color-background-unchecked-hover': string
  '--components-colors-tab-color-background-unchecked-pressed': string
  '--components-colors-tab-color-background-checked-default': string
  '--components-colors-tab-color-background-checked-hover': string
  '--components-colors-tab-color-background-checked-pressed': string
  '--components-colors-tab-color-text-unchecked-default': string
  '--components-colors-tab-color-text-unchecked-hover': string
  '--components-colors-tab-color-text-unchecked-pressed': string
  '--components-colors-tab-color-text-checked-default': string
  '--components-colors-tab-color-text-checked-hover': string
  '--components-colors-tab-color-text-checked-pressed': string
  '--components-colors-tab-color-border-unchecked-default': string
  '--components-colors-tab-color-border-unchecked-hover': string
  '--components-colors-tab-color-border-unchecked-pressed': string
  '--components-colors-tab-color-border-checked-default': string
  '--components-colors-tab-color-border-checked-hover': string
  '--components-colors-tab-color-border-checked-pressed': string
  '--components-colors-pagination-color-background-unchecked-default': string
  '--components-colors-pagination-color-background-unchecked-hover': string
  '--components-colors-pagination-color-background-unchecked-pressed': string
  '--components-colors-pagination-color-background-unchecked-disabled': string
  '--components-colors-pagination-color-background-checked-default': string
  '--components-colors-pagination-color-background-checked-hover': string
  '--components-colors-pagination-color-background-checked-pressed': string
  '--components-colors-pagination-color-background-checked-disabled': string
  '--components-colors-pagination-color-text-unchecked-default': string
  '--components-colors-pagination-color-text-unchecked-hover': string
  '--components-colors-pagination-color-text-unchecked-pressed': string
  '--components-colors-pagination-color-text-unchecked-disabled': string
  '--components-colors-pagination-color-text-checked-default': string
  '--components-colors-pagination-color-text-checked-hover': string
  '--components-colors-pagination-color-text-checked-pressed': string
  '--components-colors-pagination-color-text-checked-disabled': string
  '--components-colors-pagination-color-border-unchecked-default': string
  '--components-colors-pagination-color-border-unchecked-hover': string
  '--components-colors-pagination-color-border-unchecked-pressed': string
  '--components-colors-pagination-color-border-checked-default': string
  '--components-colors-pagination-color-border-checked-hover': string
  '--components-colors-pagination-color-border-checked-pressed': string
  '--components-colors-pagination-color-icon-unchecked-default': string
  '--components-colors-pagination-color-icon-unchecked-hover': string
  '--components-colors-pagination-color-icon-unchecked-pressed': string
  '--components-colors-pagination-color-icon-unchecked-disabled': string
  '--components-colors-pagination-color-icon-checked-default': string
  '--components-colors-pagination-color-icon-checked-hover': string
  '--components-colors-pagination-color-icon-checked-pressed': string
  '--components-colors-pagination-color-icon-checked-disabled': string
  '--components-dimensions-button-size-max-height-lg': string
  '--components-dimensions-button-size-max-height-md': string
  '--components-dimensions-button-size-max-height-sm': string
  '--components-dimensions-button-size-icon-lg': string
  '--components-dimensions-button-size-icon-md': string
  '--components-dimensions-button-size-icon-sm': string
  '--components-dimensions-button-padding-inline-lg': string
  '--components-dimensions-button-padding-inline-md': string
  '--components-dimensions-button-padding-inline-sm': string
  '--components-dimensions-button-padding-block-lg': string
  '--components-dimensions-button-padding-block-md': string
  '--components-dimensions-button-padding-block-sm': string
  '--components-dimensions-button-gap-content-lg': string
  '--components-dimensions-button-gap-content-md': string
  '--components-dimensions-button-gap-content-sm': string
  '--components-dimensions-button-border-radius': string
  '--components-dimensions-button-border-width-focused': string
  '--components-dimensions-button-border-width-ai': string
  '--components-dimensions-button-border-width-secondary': string
  '--components-dimensions-link-underline-size-height': string
  '--components-dimensions-link-size-icon-lg': string
  '--components-dimensions-link-size-icon-md': string
  '--components-dimensions-link-size-icon-sm': string
  '--components-dimensions-link-size-icon-xs': string
  '--components-dimensions-link-padding-inline-text': string
  '--components-dimensions-link-padding-inline-icon': string
  '--components-dimensions-link-gap-content': string
  '--components-dimensions-link-gap-underline': string
  '--components-dimensions-avatar-size-lg': string
  '--components-dimensions-avatar-size-md': string
  '--components-dimensions-avatar-size-sm': string
  '--components-dimensions-avatar-size-xs': string
  '--components-dimensions-avatar-border-radius': string
  '--components-dimensions-badge-size-height': string
  '--components-dimensions-badge-size-max-height-lg': string
  '--components-dimensions-badge-size-max-height-md': string
  '--components-dimensions-badge-size-min-width-lg': string
  '--components-dimensions-badge-size-min-width-md': string
  '--components-dimensions-badge-size-width': string
  '--components-dimensions-badge-padding-inline-lg': string
  '--components-dimensions-badge-padding-inline-md': string
  '--components-dimensions-badge-padding-block-lg': string
  '--components-dimensions-badge-padding-block-md': string
  '--components-dimensions-badge-border-radius-lg': string
  '--components-dimensions-badge-border-radius-md': string
  '--components-dimensions-badge-border-radius-sm': string
  '--components-dimensions-card-action-dismiss-size-icon-lg': string
  '--components-dimensions-card-action-dismiss-size-icon-md': string
  '--components-dimensions-card-action-dismiss-size-icon-sm': string
  '--components-dimensions-card-action-dismiss-padding-inline-end-lg': string
  '--components-dimensions-card-action-dismiss-padding-inline-end-md': string
  '--components-dimensions-card-action-dismiss-padding-inline-end-sm': string
  '--components-dimensions-card-action-dismiss-padding-block-start-lg': string
  '--components-dimensions-card-action-dismiss-padding-block-start-md': string
  '--components-dimensions-card-action-dismiss-padding-block-start-sm': string
  '--components-dimensions-card-size-icon-lg': string
  '--components-dimensions-card-padding-inline-lg': string
  '--components-dimensions-card-padding-inline-md': string
  '--components-dimensions-card-padding-inline-sm': string
  '--components-dimensions-card-padding-block-lg': string
  '--components-dimensions-card-padding-block-md': string
  '--components-dimensions-card-padding-block-sm': string
  '--components-dimensions-card-gap-title': string
  '--components-dimensions-card-gap-content-lg': string
  '--components-dimensions-card-gap-content-md': string
  '--components-dimensions-card-gap-content-sm': string
  '--components-dimensions-card-border-radius': string
  '--components-dimensions-tag-size-max-height-lg': string
  '--components-dimensions-tag-size-max-height-md': string
  '--components-dimensions-tag-size-icon': string
  '--components-dimensions-tag-padding-inline-lg': string
  '--components-dimensions-tag-padding-inline-md': string
  '--components-dimensions-tag-padding-block-lg': string
  '--components-dimensions-tag-padding-block-md': string
  '--components-dimensions-tag-gap-content': string
  '--components-dimensions-tag-border-radius': string
  '--components-dimensions-tag-border-width': string
  '--components-dimensions-window-header-action-size-container': string
  '--components-dimensions-window-header-action-size-icon': string
  '--components-dimensions-window-header-action-border-radius': string
  '--components-dimensions-window-header-size-min-height': string
  '--components-dimensions-window-header-tab-border-width-active': string
  '--components-dimensions-window-header-gap-content': string
  '--components-dimensions-window-header-gap-actions': string
  '--components-dimensions-window-header-padding-inline-xs': string
  '--components-dimensions-window-header-padding-block-xs': string
  '--components-dimensions-window-body-padding-inline-xs': string
  '--components-dimensions-window-body-padding-inline-sm': string
  '--components-dimensions-window-body-padding-inline-md': string
  '--components-dimensions-window-body-padding-inline-lg': string
  '--components-dimensions-window-body-padding-inline-xl': string
  '--components-dimensions-window-body-padding-block-xs': string
  '--components-dimensions-window-body-padding-block-sm': string
  '--components-dimensions-window-body-padding-block-md': string
  '--components-dimensions-window-body-padding-block-lg': string
  '--components-dimensions-window-body-padding-block-xl': string
  '--components-dimensions-window-border-radius': string
  '--components-dimensions-window-border-width': string
  '--components-dimensions-dropdown-menu-item-padding-inline': string
  '--components-dimensions-dropdown-menu-item-padding-block': string
  '--components-dimensions-dropdown-menu-item-gap-content': string
  '--components-dimensions-dropdown-menu-item-border-radius': string
  '--components-dimensions-dropdown-menu-size-icon': string
  '--components-dimensions-dropdown-menu-padding-inline': string
  '--components-dimensions-dropdown-menu-padding-block': string
  '--components-dimensions-dropdown-menu-gap-content': string
  '--components-dimensions-dropdown-menu-border-radius': string
  '--components-dimensions-dropdown-menu-border-width': string
  '--components-dimensions-callout-icon-padding-inline': string
  '--components-dimensions-callout-icon-padding-block': string
  '--components-dimensions-callout-icon-border-radius': string
  '--components-dimensions-callout-border-radius': string
  '--components-dimensions-callout-gap-content-sm': string
  '--components-dimensions-callout-gap-content-md': string
  '--components-dimensions-callout-gap-actions-sm': string
  '--components-dimensions-callout-gap-actions-md': string
  '--components-dimensions-callout-padding-inline-sm': string
  '--components-dimensions-callout-padding-inline-md': string
  '--components-dimensions-callout-padding-block-sm': string
  '--components-dimensions-callout-padding-block-md': string
  '--components-dimensions-growl-icon-size-icon': string
  '--components-dimensions-growl-icon-padding-inline': string
  '--components-dimensions-growl-icon-padding-block': string
  '--components-dimensions-growl-icon-border-radius': string
  '--components-dimensions-growl-size-icon': string
  '--components-dimensions-growl-border-radius': string
  '--components-dimensions-growl-border-width': string
  '--components-dimensions-growl-padding-inline': string
  '--components-dimensions-growl-padding-block': string
  '--components-dimensions-growl-gap-content': string
  '--components-dimensions-toast-icon-size-icon': string
  '--components-dimensions-toast-icon-padding-inline': string
  '--components-dimensions-toast-icon-padding-block': string
  '--components-dimensions-toast-icon-border-radius': string
  '--components-dimensions-toast-size-icon': string
  '--components-dimensions-toast-padding-inline': string
  '--components-dimensions-toast-padding-block': string
  '--components-dimensions-toast-gap-content': string
  '--components-dimensions-toast-border-radius': string
  '--components-dimensions-toast-border-width': string
  '--components-dimensions-tooltip-padding-inline': string
  '--components-dimensions-tooltip-padding-block': string
  '--components-dimensions-tooltip-gap-content': string
  '--components-dimensions-tooltip-border-radius': string
  '--components-dimensions-tooltip-border-width': string
  '--components-dimensions-sticky-note-icon-size-icon': string
  '--components-dimensions-sticky-note-icon-padding-inline': string
  '--components-dimensions-sticky-note-icon-padding-block': string
  '--components-dimensions-sticky-note-icon-border-radius': string
  '--components-dimensions-sticky-note-size-icon': string
  '--components-dimensions-sticky-note-size-width-square': string
  '--components-dimensions-sticky-note-size-width-rectangle': string
  '--components-dimensions-sticky-note-size-height-square': string
  '--components-dimensions-sticky-note-size-height-rectangle': string
  '--components-dimensions-sticky-note-gap-content': string
  '--components-dimensions-sticky-note-border-radius': string
  '--components-dimensions-sticky-note-border-width': string
  '--components-dimensions-field-gap-label': string
  '--components-dimensions-field-gap-assistive': string
  '--components-dimensions-label-size-leading': string
  '--components-dimensions-label-size-required': string
  '--components-dimensions-label-gap-content': string
  '--components-dimensions-input-max-height-lg': string
  '--components-dimensions-input-max-height-md': string
  '--components-dimensions-input-max-height-sm': string
  '--components-dimensions-input-padding-inline-lg': string
  '--components-dimensions-input-padding-inline-md': string
  '--components-dimensions-input-padding-inline-sm': string
  '--components-dimensions-input-padding-block-lg': string
  '--components-dimensions-input-padding-block-md': string
  '--components-dimensions-input-padding-block-sm': string
  '--components-dimensions-input-size-icon': string
  '--components-dimensions-input-size-image': string
  '--components-dimensions-input-gap-content': string
  '--components-dimensions-input-border-width-default': string
  '--components-dimensions-input-border-width-focused': string
  '--components-dimensions-input-border-radius': string
  '--components-dimensions-checkbox-border-width-default': string
  '--components-dimensions-checkbox-border-width-focused': string
  '--components-dimensions-checkbox-border-radius': string
  '--components-dimensions-checkbox-size-container': string
  '--components-dimensions-checkbox-size-icon': string
  '--components-dimensions-radio-size': string
  '--components-dimensions-radio-border-radius': string
  '--components-dimensions-radio-border-width-unchecked': string
  '--components-dimensions-radio-border-width-checked': string
  '--components-dimensions-radio-border-width-focused': string
  '--components-dimensions-radio-indicator-size': string
  '--components-dimensions-radio-indicator-border-radius': string
  '--components-dimensions-toggle-track-size-height-lg': string
  '--components-dimensions-toggle-track-size-height-md': string
  '--components-dimensions-toggle-track-size-height-sm': string
  '--components-dimensions-toggle-track-size-width-lg': string
  '--components-dimensions-toggle-track-size-width-md': string
  '--components-dimensions-toggle-track-size-width-sm': string
  '--components-dimensions-toggle-track-size-icon-lg': string
  '--components-dimensions-toggle-track-size-icon-md': string
  '--components-dimensions-toggle-track-size-icon-sm': string
  '--components-dimensions-toggle-track-border-radius': string
  '--components-dimensions-toggle-track-border-width-focused': string
  '--components-dimensions-toggle-thumb-size-lg': string
  '--components-dimensions-toggle-thumb-size-md': string
  '--components-dimensions-toggle-thumb-size-sm': string
  '--components-dimensions-toggle-thumb-border-width': string
  '--components-dimensions-file-drop-border-radius': string
  '--components-dimensions-file-drop-border-width-default': string
  '--components-dimensions-file-drop-padding-inline': string
  '--components-dimensions-file-drop-padding-block': string
  '--components-dimensions-file-drop-gap-content': string
  '--components-dimensions-breadcrumb-size-icon': string
  '--components-dimensions-breadcrumb-gap-content': string
  '--components-dimensions-stepper-size-icon': string
  '--components-dimensions-stepper-padding-inline': string
  '--components-dimensions-stepper-padding-block': string
  '--components-dimensions-stepper-gap-content': string
  '--components-dimensions-stepper-step-size-icon': string
  '--components-dimensions-stepper-step-border-radius': string
  '--components-dimensions-stepper-step-border-width-active': string
  '--components-dimensions-stepper-step-padding-inline': string
  '--components-dimensions-stepper-step-padding-block': string
  '--components-dimensions-stepper-step-gap-content': string
  '--components-dimensions-stepper-border-radius': string
  '--components-dimensions-stepper-border-width-default': string
  '--components-dimensions-tab-size-icon-lg': string
  '--components-dimensions-tab-size-icon-md': string
  '--components-dimensions-tab-size-max-height-lg': string
  '--components-dimensions-tab-size-max-height-md': string
  '--components-dimensions-tab-gap-content-lg': string
  '--components-dimensions-tab-gap-content-md': string
  '--components-dimensions-tab-gap-tabs-lg': string
  '--components-dimensions-tab-gap-tabs-md': string
  '--components-dimensions-tab-padding-inline-lg': string
  '--components-dimensions-tab-padding-inline-md': string
  '--components-dimensions-tab-padding-block-lg': string
  '--components-dimensions-tab-padding-block-md': string
  '--components-dimensions-tab-border-width-unchecked': string
  '--components-dimensions-tab-border-width-checked': string
  '--components-dimensions-pagination-size-min-width-lg': string
  '--components-dimensions-pagination-size-min-width-md': string
  '--components-dimensions-pagination-size-min-height-lg': string
  '--components-dimensions-pagination-size-min-height-md': string
  '--components-dimensions-pagination-size-icon': string
  '--components-dimensions-pagination-size-max-width-lg': string
  '--components-dimensions-pagination-size-max-width-md': string
  '--components-dimensions-pagination-size-max-height-lg': string
  '--components-dimensions-pagination-size-max-height-md': string
  '--components-dimensions-pagination-start-padding-inline-leading-lg': string
  '--components-dimensions-pagination-start-padding-inline-leading-md': string
  '--components-dimensions-pagination-start-padding-inline-trailing-lg': string
  '--components-dimensions-pagination-start-padding-inline-trailing-md': string
  '--components-dimensions-pagination-end-padding-inline-leading-lg': string
  '--components-dimensions-pagination-end-padding-inline-leading-md': string
  '--components-dimensions-pagination-end-padding-inline-trailing-lg': string
  '--components-dimensions-pagination-end-padding-inline-trailing-md': string
  '--components-dimensions-pagination-padding-inline-lg': string
  '--components-dimensions-pagination-padding-inline-md': string
  '--components-dimensions-pagination-padding-block-lg': string
  '--components-dimensions-pagination-padding-block-md': string
  '--components-dimensions-pagination-gap-content': string
  '--components-dimensions-pagination-gap-pages': string
  '--components-dimensions-pagination-border-radius': string
  '--components-dimensions-pagination-border-width-unchecked': string
  '--components-dimensions-pagination-border-width-checked': string
  '--color-yellow-10': string
  '--color-yellow-20': string
  '--color-yellow-30': string
  '--color-yellow-40': string
  '--color-yellow-50': string
  '--color-yellow-60': string
  '--color-yellow-70': string
  '--color-yellow-80': string
  '--color-yellow-90': string
  '--color-neutral-10': string
  '--color-neutral-20': string
  '--color-neutral-30': string
  '--color-neutral-40': string
  '--color-neutral-50': string
  '--color-neutral-60': string
  '--color-neutral-70': string
  '--color-neutral-80': string
  '--color-neutral-90': string
  '--color-beige-10': string
  '--color-beige-20': string
  '--color-beige-30': string
  '--color-beige-40': string
  '--color-beige-50': string
  '--color-beige-60': string
  '--color-beige-70': string
  '--color-beige-80': string
  '--color-beige-90': string
  '--color-green-10': string
  '--color-green-20': string
  '--color-green-30': string
  '--color-green-40': string
  '--color-green-50': string
  '--color-green-60': string
  '--color-green-70': string
  '--color-green-80': string
  '--color-green-90': string
  '--color-teal-10': string
  '--color-teal-20': string
  '--color-teal-30': string
  '--color-teal-40': string
  '--color-teal-50': string
  '--color-teal-60': string
  '--color-teal-70': string
  '--color-teal-80': string
  '--color-teal-90': string
  '--color-blue-10': string
  '--color-blue-20': string
  '--color-blue-30': string
  '--color-blue-40': string
  '--color-blue-50': string
  '--color-blue-60': string
  '--color-blue-70': string
  '--color-blue-80': string
  '--color-blue-90': string
  '--color-violet-10': string
  '--color-violet-20': string
  '--color-violet-30': string
  '--color-violet-40': string
  '--color-violet-50': string
  '--color-violet-60': string
  '--color-violet-70': string
  '--color-violet-80': string
  '--color-violet-90': string
  '--color-pink-10': string
  '--color-pink-20': string
  '--color-pink-30': string
  '--color-pink-40': string
  '--color-pink-50': string
  '--color-pink-60': string
  '--color-pink-70': string
  '--color-pink-80': string
  '--color-pink-90': string
  '--color-red-orange-10': string
  '--color-red-orange-20': string
  '--color-red-orange-30': string
  '--color-red-orange-40': string
  '--color-red-orange-50': string
  '--color-red-orange-60': string
  '--color-red-orange-70': string
  '--color-red-orange-80': string
  '--color-red-orange-90': string
  '--color-orange-10': string
  '--color-orange-20': string
  '--color-orange-30': string
  '--color-orange-40': string
  '--color-orange-50': string
  '--color-orange-60': string
  '--color-orange-70': string
  '--color-orange-80': string
  '--color-orange-90': string
  '--color-red-10': string
  '--color-red-20': string
  '--color-red-30': string
  '--color-red-40': string
  '--color-red-50': string
  '--color-red-60': string
  '--color-red-70': string
  '--color-red-80': string
  '--color-red-90': string
  '--color-background-brand-primary': string
  '--color-background-brand-secondary': string
  '--color-background-brand-subtle': string
  '--color-background-brand-minimal': string
  '--color-background-brand-strong': string
  '--color-background-brand-stronger': string
  '--color-background-neutral-primary': string
  '--color-background-neutral-secondary': string
  '--color-background-neutral-tertiary': string
  '--color-background-neutral-subtle': string
  '--color-background-neutral-subtlest': string
  '--color-background-neutral-minimal': string
  '--color-background-neutral-inverse': string
  '--color-background-neutral-primary-fixed': string
  '--color-background-neutral-inverse-fixed': string
  '--color-background-warm-primary': string
  '--color-background-warm-minimal': string
  '--color-background-warm-strong': string
  '--color-background-warm-stronger': string
  '--color-background-information-primary': string
  '--color-background-information-secondary': string
  '--color-background-information-subtle': string
  '--color-background-information-minimal': string
  '--color-background-information-strong': string
  '--color-background-information-stronger': string
  '--color-background-success-primary': string
  '--color-background-success-secondary': string
  '--color-background-success-minimal': string
  '--color-background-success-strong': string
  '--color-background-success-stronger': string
  '--color-background-success-strongest': string
  '--color-background-warning-primary': string
  '--color-background-warning-secondary': string
  '--color-background-warning-subtle': string
  '--color-background-warning-minimal': string
  '--color-background-warning-strong': string
  '--color-background-warning-stronger': string
  '--color-background-danger-primary': string
  '--color-background-danger-secondary': string
  '--color-background-danger-subtle': string
  '--color-background-danger-minimal': string
  '--color-background-danger-strong': string
  '--color-background-danger-stronger': string
  '--color-background-danger-strongest': string
  '--color-background-accent-green-primary': string
  '--color-background-accent-green-secondary': string
  '--color-background-accent-green-minimal': string
  '--color-background-accent-green-strong': string
  '--color-background-accent-green-stronger': string
  '--color-background-accent-green-strongest': string
  '--color-background-accent-teal-primary': string
  '--color-background-accent-teal-secondary': string
  '--color-background-accent-teal-subtle': string
  '--color-background-accent-teal-minimal': string
  '--color-background-accent-teal-strong': string
  '--color-background-accent-teal-stronger': string
  '--color-background-accent-teal-strongest': string
  '--color-background-accent-blue-primary': string
  '--color-background-accent-blue-secondary': string
  '--color-background-accent-blue-subtle': string
  '--color-background-accent-blue-minimal': string
  '--color-background-accent-blue-strong': string
  '--color-background-accent-blue-stronger': string
  '--color-background-accent-blue-strongest': string
  '--color-background-accent-violet-primary': string
  '--color-background-accent-violet-secondary': string
  '--color-background-accent-violet-subtle': string
  '--color-background-accent-violet-minimal': string
  '--color-background-accent-violet-strong': string
  '--color-background-accent-violet-stronger': string
  '--color-background-accent-violet-strongest': string
  '--color-background-accent-pink-primary': string
  '--color-background-accent-pink-secondary': string
  '--color-background-accent-pink-subtle': string
  '--color-background-accent-pink-minimal': string
  '--color-background-accent-pink-strong': string
  '--color-background-accent-pink-stronger': string
  '--color-background-accent-pink-strongest': string
  '--color-background-accent-orange-primary': string
  '--color-background-accent-orange-secondary': string
  '--color-background-accent-orange-subtle': string
  '--color-background-accent-orange-minimal': string
  '--color-background-accent-orange-strong': string
  '--color-background-accent-orange-stronger': string
  '--color-background-accent-orange-strongest': string
  '--color-background-transparent-white-subtle': string
  '--color-background-transparent-white-subtlest': string
  '--color-background-transparent-white-minimal': string
  '--color-background-transparent-white-none': string
  '--color-background-transparent-black-subtle': string
  '--color-background-transparent-black-subtlest': string
  '--color-background-transparent-black-minimal': string
  '--color-background-transparent-black-none': string
  '--color-text-brand-primary': string
  '--color-text-brand-secondary': string
  '--color-text-brand-tertiary': string
  '--color-text-brand-subtle': string
  '--color-text-brand-minimal': string
  '--color-text-neutral-primary': string
  '--color-text-neutral-secondary': string
  '--color-text-neutral-tertiary': string
  '--color-text-neutral-subtle': string
  '--color-text-neutral-subtlest': string
  '--color-text-neutral-minimal': string
  '--color-text-neutral-inverse': string
  '--color-text-neutral-primary-fixed': string
  '--color-text-neutral-inverse-fixed': string
  '--color-text-warm-primary': string
  '--color-text-warm-secondary': string
  '--color-text-warm-tertiary': string
  '--color-text-warm-subtle': string
  '--color-text-warm-minimal': string
  '--color-text-information-primary': string
  '--color-text-information-secondary': string
  '--color-text-information-tertiary': string
  '--color-text-information-subtle': string
  '--color-text-information-minimal': string
  '--color-text-success-primary': string
  '--color-text-success-secondary': string
  '--color-text-success-tertiary': string
  '--color-text-success-subtle': string
  '--color-text-success-minimal': string
  '--color-text-warning-primary': string
  '--color-text-warning-secondary': string
  '--color-text-warning-tertiary': string
  '--color-text-warning-subtle': string
  '--color-text-warning-minimal': string
  '--color-text-danger-primary': string
  '--color-text-danger-secondary': string
  '--color-text-danger-tertiary': string
  '--color-text-danger-subtle': string
  '--color-text-danger-minimal': string
  '--color-text-accent-green-primary': string
  '--color-text-accent-green-secondary': string
  '--color-text-accent-green-tertiary': string
  '--color-text-accent-green-subtle': string
  '--color-text-accent-green-minimal': string
  '--color-text-accent-teal-primary': string
  '--color-text-accent-teal-secondary': string
  '--color-text-accent-teal-tertiary': string
  '--color-text-accent-teal-subtle': string
  '--color-text-accent-teal-minimal': string
  '--color-text-accent-blue-primary': string
  '--color-text-accent-blue-secondary': string
  '--color-text-accent-blue-tertiary': string
  '--color-text-accent-blue-subtle': string
  '--color-text-accent-blue-minimal': string
  '--color-text-accent-violet-primary': string
  '--color-text-accent-violet-secondary': string
  '--color-text-accent-violet-tertiary': string
  '--color-text-accent-violet-subtle': string
  '--color-text-accent-violet-minimal': string
  '--color-text-accent-pink-primary': string
  '--color-text-accent-pink-secondary': string
  '--color-text-accent-pink-tertiary': string
  '--color-text-accent-pink-subtle': string
  '--color-text-accent-pink-minimal': string
  '--color-text-accent-orange-primary': string
  '--color-text-accent-orange-secondary': string
  '--color-text-accent-orange-tertiary': string
  '--color-text-accent-orange-subtle': string
  '--color-text-accent-orange-minimal': string
  '--color-border-brand-primary': string
  '--color-border-brand-secondary': string
  '--color-border-brand-subtle': string
  '--color-border-brand-minimal': string
  '--color-border-brand-strong': string
  '--color-border-brand-stronger': string
  '--color-border-neutral-primary': string
  '--color-border-neutral-secondary': string
  '--color-border-neutral-tertiary': string
  '--color-border-neutral-subtle': string
  '--color-border-neutral-subtlest': string
  '--color-border-neutral-minimal': string
  '--color-border-neutral-inverse': string
  '--color-border-neutral-primary-fixed': string
  '--color-border-neutral-inverse-fixed': string
  '--color-border-warm-primary': string
  '--color-border-warm-secondary': string
  '--color-border-warm-tertiary': string
  '--color-border-warm-subtle': string
  '--color-border-warm-minimal': string
  '--color-border-warm-strong': string
  '--color-border-warm-stronger': string
  '--color-border-information-primary': string
  '--color-border-information-secondary': string
  '--color-border-information-subtle': string
  '--color-border-information-minimal': string
  '--color-border-information-strong': string
  '--color-border-information-stronger': string
  '--color-border-information-strongest': string
  '--color-border-success-primary': string
  '--color-border-success-secondary': string
  '--color-border-success-minimal': string
  '--color-border-success-strong': string
  '--color-border-success-stronger': string
  '--color-border-success-strongest': string
  '--color-border-warning-primary': string
  '--color-border-warning-secondary': string
  '--color-border-warning-subtle': string
  '--color-border-warning-minimal': string
  '--color-border-warning-strong': string
  '--color-border-warning-stronger': string
  '--color-border-warning-strongest': string
  '--color-border-danger-primary': string
  '--color-border-danger-secondary': string
  '--color-border-danger-subtle': string
  '--color-border-danger-minimal': string
  '--color-border-danger-strong': string
  '--color-border-danger-stronger': string
  '--color-border-danger-strongest': string
  '--color-border-transparent-white-subtle': string
  '--color-border-transparent-white-subtlest': string
  '--color-border-transparent-white-minimal': string
  '--color-border-transparent-white-none': string
  '--color-border-transparent-black-subtle': string
  '--color-border-transparent-black-subtlest': string
  '--color-border-transparent-black-minimal': string
  '--color-border-transparent-black-none': string
  '--color-icon-brand-primary': string
  '--color-icon-brand-secondary': string
  '--color-icon-brand-tertiary': string
  '--color-icon-brand-subtle': string
  '--color-icon-brand-subtlest': string
  '--color-icon-brand-minimal': string
  '--color-icon-neutral-primary': string
  '--color-icon-neutral-secondary': string
  '--color-icon-neutral-tertiary': string
  '--color-icon-neutral-subtle': string
  '--color-icon-neutral-subtlest': string
  '--color-icon-neutral-minimal': string
  '--color-icon-neutral-inverse': string
  '--color-icon-neutral-primary-fixed': string
  '--color-icon-neutral-inverse-fixed': string
  '--color-icon-warm-primary': string
  '--color-icon-warm-secondary': string
  '--color-icon-warm-tertiary': string
  '--color-icon-warm-subtle': string
  '--color-icon-warm-minimal': string
  '--color-icon-information-primary': string
  '--color-icon-information-secondary': string
  '--color-icon-information-tertiary': string
  '--color-icon-information-subtle': string
  '--color-icon-information-subtlest': string
  '--color-icon-information-minimal': string
  '--color-icon-success-primary': string
  '--color-icon-success-secondary': string
  '--color-icon-success-tertiary': string
  '--color-icon-success-subtle': string
  '--color-icon-success-subtlest': string
  '--color-icon-success-minimal': string
  '--color-icon-warning-primary': string
  '--color-icon-warning-secondary': string
  '--color-icon-warning-tertiary': string
  '--color-icon-warning-subtle': string
  '--color-icon-warning-subtlest': string
  '--color-icon-warning-minimal': string
  '--color-icon-danger-primary': string
  '--color-icon-danger-secondary': string
  '--color-icon-danger-tertiary': string
  '--color-icon-danger-subtle': string
  '--color-icon-danger-subtlest': string
  '--color-icon-danger-minimal': string
  '--color-icon-accent-green-primary': string
  '--color-icon-accent-green-secondary': string
  '--color-icon-accent-green-tertiary': string
  '--color-icon-accent-green-subtle': string
  '--color-icon-accent-green-subtlest': string
  '--color-icon-accent-green-minimal': string
  '--color-icon-accent-teal-primary': string
  '--color-icon-accent-teal-secondary': string
  '--color-icon-accent-teal-tertiary': string
  '--color-icon-accent-teal-subtle': string
  '--color-icon-accent-teal-subtlest': string
  '--color-icon-accent-teal-minimal': string
  '--color-icon-accent-blue-primary': string
  '--color-icon-accent-blue-secondary': string
  '--color-icon-accent-blue-tertiary': string
  '--color-icon-accent-blue-subtle': string
  '--color-icon-accent-blue-subtlest': string
  '--color-icon-accent-blue-minimal': string
  '--color-icon-accent-violet-primary': string
  '--color-icon-accent-violet-secondary': string
  '--color-icon-accent-violet-tertiary': string
  '--color-icon-accent-violet-subtle': string
  '--color-icon-accent-violet-subtlest': string
  '--color-icon-accent-violet-minimal': string
  '--color-icon-accent-pink-primary': string
  '--color-icon-accent-pink-secondary': string
  '--color-icon-accent-pink-tertiary': string
  '--color-icon-accent-pink-subtle': string
  '--color-icon-accent-pink-subtlest': string
  '--color-icon-accent-pink-minimal': string
  '--color-icon-accent-orange-primary': string
  '--color-icon-accent-orange-secondary': string
  '--color-icon-accent-orange-tertiary': string
  '--color-icon-accent-orange-subtle': string
  '--color-icon-accent-orange-subtlest': string
  '--color-icon-accent-orange-minimal': string
  '--color-overlay-default': string
  '--color-overlay-strong': string
  '--color-logo-background-primary': string
  '--color-logo-mark-primary': string
  '--color-logo-mark-primary-fixed': string
  '--font-size-12': string
  '--font-size-14': string
  '--font-size-16': string
  '--font-size-18': string
  '--font-size-20': string
  '--font-size-24': string
  '--font-size-32': string
  '--font-size-36': string
  '--font-size-48': string
  '--font-size-60': string
  '--font-size-72': string
  '--font-size-xs': string
  '--font-size-sm': string
  '--font-size-md': string
  '--font-size-lg': string
  '--font-size-xl': string
  '--font-size-2xl': string
  '--font-size-xxl': string
  '--font-size-3xl': string
  '--font-size-4xl': string
  '--font-size-5xl': string
  '--font-size-6xl': string
  '--font-size-7xl': string
  '--font-family-title': string
  '--font-family-body': string
  '--font-weight-regular': string
  '--font-weight-medium': string
  '--font-weight-semi-bold': string
  '--font-weight-bold': string
  '--font-weight-black': string
  '--font-line-height-xs': string
  '--font-line-height-sm': string
  '--font-line-height-md': string
  '--font-line-height-lg': string
  '--font-letter-spacing-none': string
  '--font-letter-spacing-xs': string
  '--spacing-2': string
  '--spacing-4': string
  '--spacing-8': string
  '--spacing-12': string
  '--spacing-16': string
  '--spacing-24': string
  '--spacing-32': string
  '--spacing-48': string
  '--spacing-64': string
  '--spacing-96': string
  '--spacing-128': string
  '--spacing-192': string
  '--spacing-2xs': string
  '--spacing-xxs': string
  '--spacing-xs': string
  '--spacing-sm': string
  '--spacing-md': string
  '--spacing-lg': string
  '--spacing-xl': string
  '--spacing-2xl': string
  '--spacing-xxl': string
  '--spacing-3xl': string
  '--spacing-4xl': string
  '--spacing-5xl': string
  '--spacing-6xl': string
  '--spacing-7xl': string
  '--size-8': string
  '--size-12': string
  '--size-16': string
  '--size-20': string
  '--size-24': string
  '--size-32': string
  '--size-48': string
  '--size-64': string
  '--size-icon-xs': string
  '--size-icon-sm': string
  '--size-icon-md': string
  '--size-icon-lg': string
  '--size-icon-xl': string
  '--size-icon-2xl': string
  '--size-icon-xxl': string
  '--size-icon-3xl': string
  '--height-2': string
  '--height-8': string
  '--height-16': string
  '--height-20': string
  '--height-24': string
  '--height-25': string
  '--height-32': string
  '--height-33': string
  '--height-40': string
  '--height-43': string
  '--width-8': string
  '--width-16': string
  '--width-20': string
  '--width-28': string
  '--width-32': string
  '--width-36': string
  '--width-40': string
  '--width-44': string
  '--elevation-10': string
  '--elevation-20': string
  '--elevation-30': string
  '--elevation-40': string
  '--elevation-50': string
  '--elevation-60': string
  '--inset-5': string
  '--inset-10': string
  '--inset-20': string
  '--border-width-xs': string
  '--border-width-sm': string
  '--border-width-md': string
  '--border-width-lg': string
  '--border-radius-none': string
  '--radius-none': string
  '--border-radius-xs': string
  '--radius-xs': string
  '--border-radius-sm': string
  '--radius-sm': string
  '--border-radius-md': string
  '--radius-md': string
  '--border-radius-lg': string
  '--radius-lg': string
  '--border-radius-xl': string
  '--radius-xl': string
  '--border-radius-2xl': string
  '--border-radius-xxl': string
  '--radius-2xl': string
  '--border-radius-full': string
  '--radius-full': string
  '--breakpoint-xs': string
  '--breakpoint-sm': string
  '--breakpoint-md': string
  '--breakpoint-lg': string
  '--breakpoint-xl': string
  '--breakpoint-2xl': string
  '--breakpoint-xxl': string
  '--breakpoint-3xl': string
  '--breakpoint-4xl': string
}
