//CONSTANTS
// composants > semantics > primitives

export const components = {
  button: {
    '--border-radius-button-shape-circle': 'var(--radius-circle)',
    '--border-radius-button-shape-default': 'var(--radius-md)',
    '--border-radius-button-shape-square': 'var(--radius-md)',

    '--border-width-button-default': 'var(--border-width-sm)',

    '--font-size-button-icon-lg': 'var(--font-size-xl)',

    '--font-size-button-icon-md': 'var(--font-size-text-md)',
    '--font-size-button-icon-sm': 'var(--font-size-text-md)',
    '--font-size-button-icon-xs': 'var(--font-size-text-md)',
    '--font-size-button-lg': 'var(--font-size-sm)',

    '--font-size-button-md': 'var(--font-size-sm)',

    '--font-size-button-sm': 'var(--font-size-xs)',
    '--font-size-button-xs': 'var(--font-size-xs)',
    '--font-weight-button-default': 'var(--font-weight-bold)',

    '--height-button-lg': 'var(--height-elements-xl)',
    '--height-button-md': 'var(--height-elements-lg)',
    '--height-button-sm': 'var(--height-elements-md)',
    '--height-button-xs': 'var(--height-elements-sm)',

    '--margin-inline-end-button-icon-first-and-not-only-child': 'var(--spacing-xs)',
    '--margin-inline-start-button-icon-first-and-not-only-child': 'var(--spacing-xs)',

    '--outline-width-button-default': 'var(--border-width-md)',

    '--padding-inline-button-size-lg': 'var(--spacing-xl)',
    '--padding-inline-button-size-md': 'var(--spacing-xl)',
    '--padding-inline-button-size-sm': 'var(--spacing-sm)',
    '--padding-inline-button-size-xs': 'var(--spacing-sm)',

    '--padding-inline-button-with-icon-size-lg': 'var(--spacing-lg)',
    '--padding-inline-button-with-icon-size-md': 'var(--spacing-md)',
    '--padding-inline-button-with-icon-size-sm': 'var(--spacing-md)',
    '--padding-inline-button-with-icon-size-xs': 'var(--spacing-sm)',

    '--transition-duration-button-default': 'var(--duration-medium)',
  },
  icon: {
    '--height-icon-lg': 'var(--height-elements-md)',
    '--height-icon-md': 'var(--height-elements-sm)',
    '--height-icon-sm': 'var(--height-elements-xs)',
    '--height-icon-xl': 'var(--height-elements-xl)',
    '--height-icon-xs': 'var(--height-elements-xxs)',
    '--height-icon-xxl': 'var(--height-elements-xxl)',
  },
  text: {
    '--font-size-text-h0': 'var(--font-size-h0)',
    '--font-size-text-h1': 'var(--font-size-h1)',
    '--font-size-text-h2': 'var(--font-size-h2)',
    '--font-size-text-h3': 'var(--font-size-h3)',
    '--font-size-text-h4': 'var(--font-size-h4)',
    '--font-size-text-h5': 'var(--font-size-h5)',
    '--font-size-text-h6': 'var(--font-size-h6)',
    '--font-size-text-lg': 'var(--font-size-lg)',
    '--font-size-text-md': 'var(--font-size-md)',
    '--font-size-text-sm': 'var(--font-size-sm)',
    '--font-size-text-subtitle-md': 'var(--font-size-subtitle-md)',
    '--font-size-text-subtitle-sm': 'var(--font-size-subtitle-sm)',
    '--font-size-text-xs': 'var(--font-size-xs)',
  },
} as const

export const semantics = {
  colors: {},
  fontSizes: {
    '--font-size-h0': 'var(--font-size-65)',
    '--font-size-h1': 'var(--font-size-45)',
    '--font-size-h2': 'var(--font-size-36)',
    '--font-size-h3': 'var(--font-size-26)',
    '--font-size-h4': 'var(--font-size-20)',
    '--font-size-h5': 'var(--font-size-16)',
    '--font-size-h6': 'var(--font-size-14)',
    '--font-size-lg': 'var(--font-size-18)',
    '--font-size-md': 'var(--font-size-16)',
    '--font-size-sm': 'var(--font-size-14)',
    '--font-size-subtitle-md': 'var(--font-size-13)',
    '--font-size-subtitle-sm': 'var(--font-size-11)',
    '--font-size-xl': 'var(--font-size-24)',
    '--font-size-xs': 'var(--font-size-12)',
  },
  fontWeight: {
    '--font-weight-bold': 'var(--font-weight-600)',
    '--font-weight-medium': 'var(--font-weight-500)',
    '--font-weight-regular': 'var(--font-weight-400)',
  },
  heights: {
    '--height-elements-lg': 'var(--height-40)',
    '--height-elements-md': 'var(--height-32)',
    '--height-elements-sm': 'var(--height-24)',
    '--height-elements-xl': 'var(--height-48)',
    '--height-elements-xs': 'var(--height-16)',
    '--height-elements-xxl': 'var(--height-64)',
    '--height-elements-xxs': 'var(--height-12)',
  },
  lineHeights: {
    '--line-height-h0': 'var(--line-height-72)',
    '--line-height-h1': 'var(--line-height-48)',
    '--line-height-h2': 'var(--line-height-40)',
    '--line-height-h3': 'var(--line-height-32)',
    '--line-height-h4': 'var(--line-height-24)',
    '--line-height-h5': 'var(--line-height-20)',
    '--line-height-h6': 'var(--line-height-18)',
    '--line-height-lg': 'var(--line-height-24)',
    '--line-height-md': 'var(--line-height-18)',
    '--line-height-sm': 'var(--line-height-18)',
    '--line-height-subtitle-md': 'var(--line-height-iso-font-size)',
    '--line-height-subtitle-sm': 'var(--line-height-iso-font-size)',
    '--line-height-xs': 'var(--line-height-14)',
  },
  spacings: {
    '--spacing-3xl': 'var(--spacing-48)',
    '--spacing-4xl': 'var(--spacing-64)',
    '--spacing-5xl': 'var(--spacing-96)',
    '--spacing-6xl': 'var(--spacing-128)',
    '--spacing-7xl': 'var(--spacing-192)',
    '--spacing-lg': 'var(--spacing-16)',
    '--spacing-md': 'var(--spacing-12)',
    '--spacing-sm': 'var(--spacing-8)',
    '--spacing-xl': 'var(--spacing-24)',
    '--spacing-xs': 'var(--spacing-4)',
    '--spacing-xxl': 'var(--spacing-32)',
    '--spacing-xxs': 'var(--spacing-2)',
  },
} as const

export const primitives = {
  borders: { '--border-width-lg': '3px', '--border-width-md': '2px', '--border-width-sm': '1px' },
  colors: {},
  fontFamilies: {
    '--default-font-family': '"Work Sans", sans-serif',
    '--font-family-headings': '"welcome-font", sans-serif',
    '--font-family-icons': '"welcome-icon-font"',
  },
  fontSizes: {
    '--font-size-11': '0.6875rem',
    '--font-size-12': '0.75rem',
    '--font-size-13': '0.8125rem',
    '--font-size-14': '0.875rem',
    '--font-size-16': '1rem',
    '--font-size-18': '1.125rem',
    '--font-size-20': '1.25rem',
    '--font-size-24': '1.5rem',
    '--font-size-26': '1.625rem',
    '--font-size-36': '2.25rem',
    '--font-size-45': '2.8125rem',
    '--font-size-65': '4.0625rem',
  },
  fontWeights: {
    '--font-weight-400': '400',
    '--font-weight-500': '500',
    '--font-weight-600': '600',
  },
  heights: {
    '--height-8': '0.5rem',
    '--height-10': '0.625rem',
    '--height-12': '0.75rem',
    '--height-16': '1rem',
    '--height-20': '1.25rem',
    '--height-24': '1.5rem',
    '--height-32': '2rem',
    '--height-40': '2.5rem',
    '--height-48': '3rem',
    '--height-64': '4rem',
  },
  letterSpacings: {
    '--letter-spacing-h0': '-0.10625rem',
    '--letter-spacing-h1': '-0.075rem',
    '--letter-spacing-h2': '-0.0625rem',
    '--letter-spacing-h3': '-0.05625rem',
    '--letter-spacing-h4': '-0.0375rem',
    '--letter-spacing-h5': '-0.03125rem',
    '--letter-spacing-h6': '-0.03125rem',
    '--letter-spacing-subtitle-md': '-0.0125rem',
    '--letter-spacing-subtitle-sm': '-0.0125rem',
  },
  lineHeights: {
    '--line-height-14': '0.875rem',
    '--line-height-16': '1rem',
    '--line-height-18': '1.125rem',
    '--line-height-24': '1.5rem',
    '--line-height-32': '2rem',
    '--line-height-40': '2.5rem',
    '--line-height-48': '3rem',
    '--line-height-72': '4.5rem',
    '--line-height-iso-font-size': '1',
  },
  radii: {
    '--radius-2xl': '1.5rem',
    '--radius-circle': '100%',
    '--radius-lg': '0.5rem',
    '--radius-md': '0.25rem',
    '--radius-sm': '0.125rem',
    '--radius-xl': '1rem',
  },
  screens: {
    '--breakpoint-2xl': '1440px',
    '--breakpoint-3xl': '1620px',
    '--breakpoint-4xl': '1920px',
    '--breakpoint-lg': '980px',
    '--breakpoint-md': '736px',
    '--breakpoint-sm': '480px',
    '--breakpoint-xl': '1280px',
    '--breakpoint-xs': '0px',
  },
  shadows: {
    '--shadow-focus': '0 0 0 2px var(--color-brand-40)',
    '--shadow-focus-danger': '0 0 0 2px var(--color-red-30)',
    '--shadow-focus-success': '0 0 0 2px var(--color-green-30)',
    '--shadow-focus-warning': '0 0 0 2px var(--color-orange-20)',
    '--shadow-md': '3px 4px 10px 0 color-mix(in oklab, var(--color-neutral-90) 7%, transparent)',
    '--shadow-sm': '1px 2px 4px 0 color-mix(in oklab, var(--color-neutral-90) 5%, transparent)',
  },
  spacings: {
    '--spacing-2': '0.125rem',
    '--spacing-4': '0.25rem',
    '--spacing-8': '0.5rem',
    '--spacing-12': '0.75rem',
    '--spacing-16': '1rem',
    '--spacing-24': '1.5rem',
    '--spacing-32': '2rem',
    '--spacing-48': '3rem',
    '--spacing-64': '4rem',
    '--spacing-96': '6rem',
    '--spacing-128': '8rem',
    '--spacing-192': '12rem',
  },
  transitions: {
    '--duration-fast': '100ms',
    '--duration-medium': '300ms',
    '--duration-slow': '500ms',
    '--timing-primary': 'ease',
    '--timing-secondary': 'linear',
    '--timing-tertiary': 'cubic-bezier(0.41, 0.094, 0.54, 0.07)',
  },
} as const
