name: Github release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    name: Create new github release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npx extract-changelog-release > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Pre-release
        uses: softprops/action-gh-release@v1
        if: github.ref.includes('-') === true
        with:
          files: Release.txt
          prerelease: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref.includes('-') === false
        with:
          files: Release.txt
