name: Github release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Create new github release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get
        id: get
        run: npx extract-changelog-release > RELEASE.md
      - name: Pre-release
        uses: ncipollo/release-action@v1
        if: contains(github.ref, '-') == true
        with:
          bodyFile: "RELEASE.md"
          prerelease: true
      - name: Release
        uses: ncipollo/release-action@v1
        if: contains(github.ref, '-') == false
        with:
          bodyFile: "RELEASE.md"
