name: Github release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Create new github release
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get
        id: get
        run: npx lerna-changelog > RELEASE.md
      - name: Release
        uses: ncipollo/release-action@v1
        if: contains(github.ref, '-') == false
        with:
          bodyFile: 'RELEASE.md'
